In [1]:
import json
from pathlib import Path
from imgnet.collections.store import IndexedDatasets
from imgnet.collections.source import ZenodoSource
from imgtools.nifti.crawl import Crawler
from rich import print

/home/gpudual/bhklab/josh/med-image_index/.pixi/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [32]:
indexed_datasets = IndexedDatasets("indexed_datasets") # This will download the latest version of the indexed_datasets if you dont provide a path
print(indexed_datasets.collections[:10])

14:53:10 [info     ] Indexed datasets path: /home/gpudual/bhklab/josh/med-image_index/notebooks/indexed_datasets [imgnet] call=store.__init__:57

[
    '4D-Lung',
    'ACRIN-6698',
    'ACRIN-Contralateral-Breast-MR',
    'ACRIN-FLT-Breast',
    'ACRIN-NSCLC-FDG-PET',
    'AMOS',
    'Adrenal-ACC-Ki67-Seg',
    'Advanced-MRI-Breast-Lesions',
    'Anti-PD-1_Lung',
    'B-mode-and-CEUS-Liver'
]

In [28]:
description = """
Despite the considerable progress in automatic abdominal multi-organ segmentation from CT/MRI scans in recent years, a comprehensive evaluation of the models' capabilities is hampered by the lack of a large-scale benchmark from diverse clinical scenarios. Constraint by the high cost of collecting and labeling 3D medical data, most of the deep learning models to date are driven by datasets with a limited number of organs of interest or samples, which still limits the power of modern deep models and makes it difficult to provide a fully comprehensive and fair estimate of various methods. To mitigate the limitations, we present AMOS, a large-scale, diverse, clinical dataset for abdominal organ segmentation. <u>AMOS provides 500 CT and 100 MRI scans collected from multi-center, multi-vendor, multi-modality, multi-phase, multi-disease patients, each with voxel-level annotations of 15 abdominal organs, providing challenging examples and test-bed for studying robust segmentation algorithms</u> under diverse targets and scenarios. We further benchmark several state-of-the-art medical segmentation models to evaluate the status of the existing methods on this new challenging dataset. We have made our datasets, benchmark servers, and baselines publicly available, and hope to inspire future research.  For more details, please refer to our paper "https://arxiv.org/pdf/2206.08023.pdf" as well as homepage "https://jiyuanfeng.github.io/AMOS/".

AMOS provides the following content. imagesTr and labelsTr provide 240 scans (200 CT and 40 MRI), imagesVa and labelsVa provide 120 scans for model selection (100 CT and 20 MRI), and imagesTs provide 120 test data (please submit your predictions from https://amos22.grand-challenge.org/evaluation/challenge/submissions to get a score). Please note that id numbers less than 500 belong to CT data, otherwise they belong to MRI data.
"""

source = ZenodoSource(
    file_type="nifti",
    source="zenodo",
    record_id="7155725",
    description=description,
)

In [29]:
dataset_index_path = (indexed_datasets.imgtools_path / "AMOS")
dataset_index_path.mkdir(parents=True, exist_ok=True)
with open(dataset_index_path / "source.json", "w") as f:
    json.dump(source.model_dump(mode="json"), f, indent=2)

In [33]:
print(indexed_datasets.source_config("AMOS"))

ZenodoSource(
    file_type=<FileType.NIFTI: 'nifti'>,
    source='zenodo',
    record_id='7155725',
    filenames=None,
    post_download=['unzip'],
    description='Despite the considerable progress in automatic abdominal multi-organ segmentation from CT/MRI
scans in recent years, a comprehensive evaluation of the models\' capabilities is hampered by the lack of a
large-scale benchmark from diverse clinical scenarios. Constraint by the high cost of collecting and labeling 3D
medical data, most of the deep learning models to date are driven by datasets with a limited number of organs of
interest or samples, which still limits the power of modern deep models and makes it difficult to provide a fully
comprehensive and fair estimate of various methods. To mitigate the limitations, we present AMOS, a large-scale,
diverse, clinical dataset for abdominal organ segmentation. <u>AMOS provides 500 CT and 100 MRI scans collected
from multi-center, multi-vendor, multi-modality, multi-phase, multi-disease patients, each with voxel-level
annotations of 15 abdominal organs, providing challenging examples and test-bed for studying robust segmentation
algorithms</u> under diverse targets and scenarios. We further benchmark several state-of-the-art medical
segmentation models to evaluate the status of the existing methods on this new challenging dataset. We have made
our datasets, benchmark servers, and baselines publicly available, and hope to inspire future research.  For more
details, please refer to our paper "https://arxiv.org/pdf/2206.08023.pdf" as well as homepage
"https://jiyuanfeng.github.io/AMOS/".\n\nAMOS provides the following content. imagesTr and labelsTr provide 240
scans (200 CT and 40 MRI), imagesVa and labelsVa provide 120 scans for model selection (100 CT and 20 MRI), and
imagesTs provide 120 test data (please submit your predictions from
https://amos22.grand-challenge.org/evaluation/challenge/submissions to get a score). Please note that id numbers
less than 500 belong to CT data, otherwise they belong to MRI data.\n'
)

In [ ]:
temp_data_path = Path("temp_data") / "AMOS"
temp_data_path.mkdir(parents=True, exist_ok=True)
downloader = indexed_datasets.downloader("AMOS").download(temp_data_path)

amos22.zip:   1%|          | 285M/24.2G [01:20<1:37:13, 4.11MB/s]

In [11]:
import imgtools.loggers
import logging

imgtools.loggers.get_logger("imgtools").setLevel(logging.INFO)

crawler = Crawler(
    nifti_dir=temp_data_path,
    scan_name_pattern="amos22/images{Split}/amos_{ImageID:d}.nii.gz",
    mask_name_pattern="amos22/labels{Split}/amos_{ImageID:d}.nii.gz",
    output_dir=indexed_datasets.imgtools_path,
    n_jobs=10,
    force=True,
    deep=True,
)
crawler.crawl()

12:28:26 [info     ] Starting NIFTI crawl.          [imgtools] nifti_dir=PosixPath('temp_data/AMOS') output_dir=PosixPath('indexed_datasets/.imgtools') dataset_name=None call=crawler.crawl:78
         [info     ] Found 1191 NIfTI files in /home/gpudual/bhklab/josh/med-image_index/notebooks/temp_data/AMOS. [imgtools] call=parse_niftis.parse_nifti_dir:426
         [info     ] Using shared keys: ['Split', 'ImageID'] for reference_id, this will be used to link masks to their referenced scans [imgtools] call=parse_niftis.parse_nifti_dir:447
Parsing 1191 files:  78%|███████▊  | 932/1191 [24:16<36:40,  8.49s/it]  /home/gpudual/bhklab/josh/med-image_index/.pixi/envs/default/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
14:12:23 [info     ] Parsing all NIfTI files took 6236.9513 seconds [imgtools] call=timer_utils.__exit__:58
         [warning  ] Some files did not match any pattern. [imgtools] unmatched_count=231 total_count=1191 example_paths=['__MACOSX/amos22/imagesTr/._amos_0092.nii.gz', '__MACOSX/amos22/imagesTr/._amos_0099.nii.gz', '__MACOSX/amos22/imagesTr/._amos_0102.nii.gz', '__MACOSX/amos22/imagesTr/._amos_0103.nii.gz', '__MACOSX/amos22/imagesTr/._amos_0133.nii.gz'] patterns_tried=['amos22/images{Split}/amos_{ImageID:d}.nii.gz', 'amos22/labels{Split}/amos_{ImageID:d}.nii.gz'] hint='Check that patterns include all path segments between root and filename.' call=parse_niftis._log_unmatched_summary:189
         [info     ] Saved index.                   [imgtools] path=indexed_datasets/.imgtools/AMOS/index.csv rows=960 call=parse_niftis.parse_nifti_dir:492

In [17]:
index_df = indexed_datasets.index("AMOS")

In [18]:
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.feret_diameter,mask.roundness,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality
0,Tr,1,amos22/imagesTr/amos_0001.nii.gz,scan,Tr_1,MedImage,7afee8a38d53124559a13a6781f122286d3430f7,"(768, 768, 90)",3,53084160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
1,Tr,4,amos22/imagesTr/amos_0004.nii.gz,scan,Tr_4,MedImage,c30d47e4286bcdfd0de0e7a91f2c83fdbf5f6c73,"(512, 512, 78)",3,20447232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
2,Tr,5,amos22/imagesTr/amos_0005.nii.gz,scan,Tr_5,MedImage,291404b6eca6b90014134fc09166a5b0c67d0191,"(768, 768, 80)",3,47185920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
3,Tr,6,amos22/imagesTr/amos_0006.nii.gz,scan,Tr_6,MedImage,a0dbfbc847622c27f8379106bd829d64bd77d77c,"(512, 512, 99)",3,25952256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
4,Tr,7,amos22/imagesTr/amos_0007.nii.gz,scan,Tr_7,MedImage,ca96ae6008c490bdc46ab0f89474e7e03ce6217b,"(768, 768, 107)",3,63111168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,Va,573,amos22/labelsVa/amos_0573.nii.gz,mask,Va_573,Mask,f2333983065ac98b2a71b1457951aea05d3315db,"(320, 260, 72)",3,5990400,...,235.443000,0.420071,1.157307,1.728001,74.748770,70213.070716,"(113.01956759593764, 130.79836259630235, 226.0...",3.0,amos22/imagesVa/amos_0573.nii.gz,SEG
956,Va,575,amos22/labelsVa/amos_0575.nii.gz,mask,Va_575,Mask,3db4550bfed09c738dc7b18012dc2d7e0f455799,"(260, 144, 320)",3,11980800,...,366.223913,0.382038,1.387391,1.378596,90.089618,101990.413850,"(130.14465587173495, 180.56158393522423, 248.9...",3.0,amos22/imagesVa/amos_0575.nii.gz,SEG
957,Va,576,amos22/labelsVa/amos_0576.nii.gz,mask,Va_576,Mask,17f722934f527aa4b4d8548d7117eb6c7b85e1a8,"(320, 260, 72)",3,5990400,...,284.810525,0.399127,1.168343,1.550508,84.699301,90150.784847,"(131.93846318752645, 154.14944500519806, 239.0...",13.0,amos22/imagesVa/amos_0576.nii.gz,SEG
958,Va,581,amos22/labelsVa/amos_0581.nii.gz,mask,Va_581,Mask,56423d0ec2e8d532cacbfccf0ca743e2650b96a2,"(576, 468, 72)",3,19408896,...,284.968694,0.478873,1.336116,1.461998,85.326695,91491.281922,"(123.94713972021772, 165.60775457070784, 242.1...",2.0,amos22/imagesVa/amos_0581.nii.gz,SEG
959,Va,598,amos22/labelsVa/amos_0598.nii.gz,mask,Va_598,Mask,cfdeb7dd13d9c8eef39ab4b5a760b635c69ac3f3,"(260, 144, 320)",3,11980800,...,362.489978,0.376115,1.781415,1.236302,76.943835,74397.359546,"(97.57059311170033, 173.81370215980712, 214.88...",6.0,amos22/imagesVa/amos_0598.nii.gz,SEG

In [20]:
def map_modality(row):
    if row["file_type"] == "scan":
        id = row["ImageID"]
        if id <= 500:
            return "CT"
        else:
            return "MR"
    elif row["file_type"] == "mask":
        return "SEG"

index_df["Modality"] = index_df.apply(map_modality, axis=1)
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.feret_diameter,mask.roundness,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality
0,Tr,1,amos22/imagesTr/amos_0001.nii.gz,scan,Tr_1,MedImage,7afee8a38d53124559a13a6781f122286d3430f7,"(768, 768, 90)",3,53084160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
1,Tr,4,amos22/imagesTr/amos_0004.nii.gz,scan,Tr_4,MedImage,c30d47e4286bcdfd0de0e7a91f2c83fdbf5f6c73,"(512, 512, 78)",3,20447232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
2,Tr,5,amos22/imagesTr/amos_0005.nii.gz,scan,Tr_5,MedImage,291404b6eca6b90014134fc09166a5b0c67d0191,"(768, 768, 80)",3,47185920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
3,Tr,6,amos22/imagesTr/amos_0006.nii.gz,scan,Tr_6,MedImage,a0dbfbc847622c27f8379106bd829d64bd77d77c,"(512, 512, 99)",3,25952256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
4,Tr,7,amos22/imagesTr/amos_0007.nii.gz,scan,Tr_7,MedImage,ca96ae6008c490bdc46ab0f89474e7e03ce6217b,"(768, 768, 107)",3,63111168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,Va,573,amos22/labelsVa/amos_0573.nii.gz,mask,Va_573,Mask,f2333983065ac98b2a71b1457951aea05d3315db,"(320, 260, 72)",3,5990400,...,235.443000,0.420071,1.157307,1.728001,74.748770,70213.070716,"(113.01956759593764, 130.79836259630235, 226.0...",3.0,amos22/imagesVa/amos_0573.nii.gz,SEG
956,Va,575,amos22/labelsVa/amos_0575.nii.gz,mask,Va_575,Mask,3db4550bfed09c738dc7b18012dc2d7e0f455799,"(260, 144, 320)",3,11980800,...,366.223913,0.382038,1.387391,1.378596,90.089618,101990.413850,"(130.14465587173495, 180.56158393522423, 248.9...",3.0,amos22/imagesVa/amos_0575.nii.gz,SEG
957,Va,576,amos22/labelsVa/amos_0576.nii.gz,mask,Va_576,Mask,17f722934f527aa4b4d8548d7117eb6c7b85e1a8,"(320, 260, 72)",3,5990400,...,284.810525,0.399127,1.168343,1.550508,84.699301,90150.784847,"(131.93846318752645, 154.14944500519806, 239.0...",13.0,amos22/imagesVa/amos_0576.nii.gz,SEG
958,Va,581,amos22/labelsVa/amos_0581.nii.gz,mask,Va_581,Mask,56423d0ec2e8d532cacbfccf0ca743e2650b96a2,"(576, 468, 72)",3,19408896,...,284.968694,0.478873,1.336116,1.461998,85.326695,91491.281922,"(123.94713972021772, 165.60775457070784, 242.1...",2.0,amos22/imagesVa/amos_0581.nii.gz,SEG
959,Va,598,amos22/labelsVa/amos_0598.nii.gz,mask,Va_598,Mask,cfdeb7dd13d9c8eef39ab4b5a760b635c69ac3f3,"(260, 144, 320)",3,11980800,...,362.489978,0.376115,1.781415,1.236302,76.943835,74397.359546,"(97.57059311170033, 173.81370215980712, 214.88...",6.0,amos22/imagesVa/amos_0598.nii.gz,SEG

In [34]:
index_df["BodyPartExamined"] = "ABDOMEN"

In [36]:
import json

dataset_json = temp_data_path / "amos22" / "dataset.json"
with open(dataset_json, "r") as f:
    dataset = json.load(f)

dataset

{'name': 'AMOS',
 'description': 'Amos: A large-scale abdominal multi-organ benchmark for versatile medical image segmentation',
 'author': 'Yuanfeng Ji',
 'reference': 'SRIDB x CUHKSZ x HKU x LGCHSZ x LGPHSZ',
 'licence': 'CC-BY-SA 4.0',
 'release': '1.0 01/05/2022',
 'contact': 'u3008013@connect.hku.hk',
 'tensorImageSize': '3D',
 'modality': {'0': 'CT'},
 'labels': {'0': 'background',
  '1': 'spleen',
  '2': 'right kidney',
  '3': 'left kidney',
  '4': 'gall bladder',
  '5': 'esophagus',
  '6': 'liver',
  '7': 'stomach',
  '8': 'arota',
  '9': 'postcava',
  '10': 'pancreas',
  '11': 'right adrenal gland',
  '12': 'left adrenal gland',
  '13': 'duodenum',
  '14': 'bladder',
  '15': 'prostate/uterus'},
 'numTraining': 240,
 'numValidation': 120,
 'numTest': 240,
 'training': [{'image': './imagesTr/amos_0001.nii.gz',
   'label': './labelsTr/amos_0001.nii.gz'},
  {'image': './imagesTr/amos_0004.nii.gz',
   'label': './labelsTr/amos_0004.nii.gz'},
  {'image': './imagesTr/amos_0005.nii.gz',
   'label': './labelsTr/amos_0005.nii.gz'},
  {'image': './imagesTr/amos_0006.nii.gz',
   'label': './labelsTr/amos_0006.nii.gz'},
  {'image': './imagesTr/amos_0007.nii.gz',
   'label': './labelsTr/amos_0007.nii.gz'},
  {'image': './imagesTr/amos_0009.nii.gz',
   'label': './labelsTr/amos_0009.nii.gz'},
  {'image': './imagesTr/amos_0010.nii.gz',
   'label': './labelsTr/amos_0010.nii.gz'},
  {'image': './imagesTr/amos_0011.nii.gz',
   'label': './labelsTr/amos_0011.nii.gz'},
  {'image': './imagesTr/amos_0014.nii.gz',
   'label': './labelsTr/amos_0014.nii.gz'},
  {'image': './imagesTr/amos_0015.nii.gz',
   'label': './labelsTr/amos_0015.nii.gz'},
  {'image': './imagesTr/amos_0016.nii.gz',
   'label': './labelsTr/amos_0016.nii.gz'},
  {'image': './imagesTr/amos_0017.nii.gz',
   'label': './labelsTr/amos_0017.nii.gz'},
  {'image': './imagesTr/amos_0019.nii.gz',
   'label': './labelsTr/amos_0019.nii.gz'},
  {'image': './imagesTr/amos_0021.nii.gz',
   'label': './labelsTr/amos_0021.nii.gz'},
  {'image': './imagesTr/amos_0023.nii.gz',
   'label': './labelsTr/amos_0023.nii.gz'},
  {'image': './imagesTr/amos_0024.nii.gz',
   'label': './labelsTr/amos_0024.nii.gz'},
  {'image': './imagesTr/amos_0025.nii.gz',
   'label': './labelsTr/amos_0025.nii.gz'},
  {'image': './imagesTr/amos_0027.nii.gz',
   'label': './labelsTr/amos_0027.nii.gz'},
  {'image': './imagesTr/amos_0030.nii.gz',
   'label': './labelsTr/amos_0030.nii.gz'},
  {'image': './imagesTr/amos_0033.nii.gz',
   'label': './labelsTr/amos_0033.nii.gz'},
  {'image': './imagesTr/amos_0035.nii.gz',
   'label': './labelsTr/amos_0035.nii.gz'},
  {'image': './imagesTr/amos_0036.nii.gz',
   'label': './labelsTr/amos_0036.nii.gz'},
  {'image': './imagesTr/amos_0038.nii.gz',
   'label': './labelsTr/amos_0038.nii.gz'},
  {'image': './imagesTr/amos_0042.nii.gz',
   'label': './labelsTr/amos_0042.nii.gz'},
  {'image': './imagesTr/amos_0043.nii.gz',
   'label': './labelsTr/amos_0043.nii.gz'},
  {'image': './imagesTr/amos_0044.nii.gz',
   'label': './labelsTr/amos_0044.nii.gz'},
  {'image': './imagesTr/amos_0045.nii.gz',
   'label': './labelsTr/amos_0045.nii.gz'},
  {'image': './imagesTr/amos_0047.nii.gz',
   'label': './labelsTr/amos_0047.nii.gz'},
  {'image': './imagesTr/amos_0048.nii.gz',
   'label': './labelsTr/amos_0048.nii.gz'},
  {'image': './imagesTr/amos_0049.nii.gz',
   'label': './labelsTr/amos_0049.nii.gz'},
  {'image': './imagesTr/amos_0050.nii.gz',
   'label': './labelsTr/amos_0050.nii.gz'},
  {'image': './imagesTr/amos_0052.nii.gz',
   'label': './labelsTr/amos_0052.nii.gz'},
  {'image': './imagesTr/amos_0054.nii.gz',
   'label': './labelsTr/amos_0054.nii.gz'},
  {'image': './imagesTr/amos_0057.nii.gz',
   'label': './labelsTr/amos_0057.nii.gz'},
  {'image': './imagesTr/amos_0058.nii.gz',
   'label': './labelsTr/amos_0058.nii.gz'},
  {'image': './imagesTr/amos_0059.nii.gz',
   'label': './labelsTr/amos_0059.nii.gz'},
  {'image': './imagesTr/amos_0060.nii.gz',
   'label': './labelsTr/amos_0060.nii.gz'},
  {'image': './imagesTr/amos_0064.nii.gz',
   'label': './labelsTr/amos_0064.nii.gz'},
  {'image': './imagesTr/amos_0066.nii.gz',
   'label': './labelsTr/amos_0066.nii.gz'},
  {'image': './imagesTr/amos_0067.nii.gz',
   'label': './labelsTr/amos_0067.nii.gz'},
  {'image': './imagesTr/amos_0069.nii.gz',
   'label': './labelsTr/amos_0069.nii.gz'},
  {'image': './imagesTr/amos_0071.nii.gz',
   'label': './labelsTr/amos_0071.nii.gz'},
  {'image': './imagesTr/amos_0072.nii.gz',
   'label': './labelsTr/amos_0072.nii.gz'},
  {'image': './imagesTr/amos_0075.nii.gz',
   'label': './labelsTr/amos_0075.nii.gz'},
  {'image': './imagesTr/amos_0076.nii.gz',
   'label': './labelsTr/amos_0076.nii.gz'},
  {'image': './imagesTr/amos_0077.nii.gz',
   'label': './labelsTr/amos_0077.nii.gz'},
  {'image': './imagesTr/amos_0078.nii.gz',
   'label': './labelsTr/amos_0078.nii.gz'},
  {'image': './imagesTr/amos_0079.nii.gz',
   'label': './labelsTr/amos_0079.nii.gz'},
  {'image': './imagesTr/amos_0081.nii.gz',
   'label': './labelsTr/amos_0081.nii.gz'},
  {'image': './imagesTr/amos_0083.nii.gz',
   'label': './labelsTr/amos_0083.nii.gz'},
  {'image': './imagesTr/amos_0084.nii.gz',
   'label': './labelsTr/amos_0084.nii.gz'},
  {'image': './imagesTr/amos_0086.nii.gz',
   'label': './labelsTr/amos_0086.nii.gz'},
  {'image': './imagesTr/amos_0088.nii.gz',
   'label': './labelsTr/amos_0088.nii.gz'},
  {'image': './imagesTr/amos_0089.nii.gz',
   'label': './labelsTr/amos_0089.nii.gz'},
  {'image': './imagesTr/amos_0092.nii.gz',
   'label': './labelsTr/amos_0092.nii.gz'},
  {'image': './imagesTr/amos_0094.nii.gz',
   'label': './labelsTr/amos_0094.nii.gz'},
  {'image': './imagesTr/amos_0097.nii.gz',
   'label': './labelsTr/amos_0097.nii.gz'},
  {'image': './imagesTr/amos_0098.nii.gz',
   'label': './labelsTr/amos_0098.nii.gz'},
  {'image': './imagesTr/amos_0099.nii.gz',
   'label': './labelsTr/amos_0099.nii.gz'},
  {'image': './imagesTr/amos_0102.nii.gz',
   'label': './labelsTr/amos_0102.nii.gz'},
  {'image': './imagesTr/amos_0103.nii.gz',
   'label': './labelsTr/amos_0103.nii.gz'},
  {'image': './imagesTr/amos_0104.nii.gz',
   'label': './labelsTr/amos_0104.nii.gz'},
  {'image': './imagesTr/amos_0105.nii.gz',
   'label': './labelsTr/amos_0105.nii.gz'},
  {'image': './imagesTr/amos_0109.nii.gz',
   'label': './labelsTr/amos_0109.nii.gz'},
  {'image': './imagesTr/amos_0110.nii.gz',
   'label': './labelsTr/amos_0110.nii.gz'},
  {'image': './imagesTr/amos_0111.nii.gz',
   'label': './labelsTr/amos_0111.nii.gz'},
  {'image': './imagesTr/amos_0113.nii.gz',
   'label': './labelsTr/amos_0113.nii.gz'},
  {'image': './imagesTr/amos_0115.nii.gz',
   'label': './labelsTr/amos_0115.nii.gz'},
  {'image': './imagesTr/amos_0116.nii.gz',
   'label': './labelsTr/amos_0116.nii.gz'},
  {'image': './imagesTr/amos_0118.nii.gz',
   'label': './labelsTr/amos_0118.nii.gz'},
  {'image': './imagesTr/amos_0119.nii.gz',
   'label': './labelsTr/amos_0119.nii.gz'},
  {'image': './imagesTr/amos_0121.nii.gz',
   'label': './labelsTr/amos_0121.nii.gz'},
  {'image': './imagesTr/amos_0124.nii.gz',
   'label': './labelsTr/amos_0124.nii.gz'},
  {'image': './imagesTr/amos_0125.nii.gz',
   'label': './labelsTr/amos_0125.nii.gz'},
  {'image': './imagesTr/amos_0126.nii.gz',
   'label': './labelsTr/amos_0126.nii.gz'},
  {'image': './imagesTr/amos_0127.nii.gz',
   'label': './labelsTr/amos_0127.nii.gz'},
  {'image': './imagesTr/amos_0129.nii.gz',
   'label': './labelsTr/amos_0129.nii.gz'},
  {'image': './imagesTr/amos_0131.nii.gz',
   'label': './labelsTr/amos_0131.nii.gz'},
  {'image': './imagesTr/amos_0133.nii.gz',
   'label': './labelsTr/amos_0133.nii.gz'},
  {'image': './imagesTr/amos_0134.nii.gz',
   'label': './labelsTr/amos_0134.nii.gz'},
  {'image': './imagesTr/amos_0135.nii.gz',
   'label': './labelsTr/amos_0135.nii.gz'},
  {'image': './imagesTr/amos_0137.nii.gz',
   'label': './labelsTr/amos_0137.nii.gz'},
  {'image': './imagesTr/amos_0138.nii.gz',
   'label': './labelsTr/amos_0138.nii.gz'},
  {'image': './imagesTr/amos_0141.nii.gz',
   'label': './labelsTr/amos_0141.nii.gz'},
  {'image': './imagesTr/amos_0142.nii.gz',
   'label': './labelsTr/amos_0142.nii.gz'},
  {'image': './imagesTr/amos_0143.nii.gz',
   'label': './labelsTr/amos_0143.nii.gz'},
  {'image': './imagesTr/amos_0147.nii.gz',
   'label': './labelsTr/amos_0147.nii.gz'},
  {'image': './imagesTr/amos_0149.nii.gz',
   'label': './labelsTr/amos_0149.nii.gz'},
  {'image': './imagesTr/amos_0152.nii.gz',
   'label': './labelsTr/amos_0152.nii.gz'},
  {'image': './imagesTr/amos_0153.nii.gz',
   'label': './labelsTr/amos_0153.nii.gz'},
  {'image': './imagesTr/amos_0154.nii.gz',
   'label': './labelsTr/amos_0154.nii.gz'},
  {'image': './imagesTr/amos_0156.nii.gz',
   'label': './labelsTr/amos_0156.nii.gz'},
  {'image': './imagesTr/amos_0158.nii.gz',
   'label': './labelsTr/amos_0158.nii.gz'},
  {'image': './imagesTr/amos_0159.nii.gz',
   'label': './labelsTr/amos_0159.nii.gz'},
  {'image': './imagesTr/amos_0160.nii.gz',
   'label': './labelsTr/amos_0160.nii.gz'},
  {'image': './imagesTr/amos_0161.nii.gz',
   'label': './labelsTr/amos_0161.nii.gz'},
  {'image': './imagesTr/amos_0162.nii.gz',
   'label': './labelsTr/amos_0162.nii.gz'},
  {'image': './imagesTr/amos_0166.nii.gz',
   'label': './labelsTr/amos_0166.nii.gz'},
  {'image': './imagesTr/amos_0170.nii.gz',
   'label': './labelsTr/amos_0170.nii.gz'},
  {'image': './imagesTr/amos_0171.nii.gz',
   'label': './labelsTr/amos_0171.nii.gz'},
  {'image': './imagesTr/amos_0172.nii.gz',
   'label': './labelsTr/amos_0172.nii.gz'},
  {'image': './imagesTr/amos_0173.nii.gz',
   'label': './labelsTr/amos_0173.nii.gz'},
  {'image': './imagesTr/amos_0175.nii.gz',
   'label': './labelsTr/amos_0175.nii.gz'},
  {'image': './imagesTr/amos_0177.nii.gz',
   'label': './labelsTr/amos_0177.nii.gz'},
  {'image': './imagesTr/amos_0179.nii.gz',
   'label': './labelsTr/amos_0179.nii.gz'},
  {'image': './imagesTr/amos_0180.nii.gz',
   'label': './labelsTr/amos_0180.nii.gz'},
  {'image': './imagesTr/amos_0181.nii.gz',
   'label': './labelsTr/amos_0181.nii.gz'},
  {'image': './imagesTr/amos_0184.nii.gz',
   'label': './labelsTr/amos_0184.nii.gz'},
  {'image': './imagesTr/amos_0185.nii.gz',
   'label': './labelsTr/amos_0185.nii.gz'},
  {'image': './imagesTr/amos_0186.nii.gz',
   'label': './labelsTr/amos_0186.nii.gz'},
  {'image': './imagesTr/amos_0188.nii.gz',
   'label': './labelsTr/amos_0188.nii.gz'},
  {'image': './imagesTr/amos_0190.nii.gz',
   'label': './labelsTr/amos_0190.nii.gz'},
  {'image': './imagesTr/amos_0192.nii.gz',
   'label': './labelsTr/amos_0192.nii.gz'},
  {'image': './imagesTr/amos_0193.nii.gz',
   'label': './labelsTr/amos_0193.nii.gz'},
  {'image': './imagesTr/amos_0195.nii.gz',
   'label': './labelsTr/amos_0195.nii.gz'},
  {'image': './imagesTr/amos_0196.nii.gz',
   'label': './labelsTr/amos_0196.nii.gz'},
  {'image': './imagesTr/amos_0197.nii.gz',
   'label': './labelsTr/amos_0197.nii.gz'},
  {'image': './imagesTr/amos_0198.nii.gz',
   'label': './labelsTr/amos_0198.nii.gz'},
  {'image': './imagesTr/amos_0199.nii.gz',
   'label': './labelsTr/amos_0199.nii.gz'},
  {'image': './imagesTr/amos_0212.nii.gz',
   'label': './labelsTr/amos_0212.nii.gz'},
  {'image': './imagesTr/amos_0214.nii.gz',
   'label': './labelsTr/amos_0214.nii.gz'},
  {'image': './imagesTr/amos_0215.nii.gz',
   'label': './labelsTr/amos_0215.nii.gz'},
  {'image': './imagesTr/amos_0217.nii.gz',
   'label': './labelsTr/amos_0217.nii.gz'},
  {'image': './imagesTr/amos_0224.nii.gz',
   'label': './labelsTr/amos_0224.nii.gz'},
  {'image': './imagesTr/amos_0225.nii.gz',
   'label': './labelsTr/amos_0225.nii.gz'},
  {'image': './imagesTr/amos_0226.nii.gz',
   'label': './labelsTr/amos_0226.nii.gz'},
  {'image': './imagesTr/amos_0230.nii.gz',
   'label': './labelsTr/amos_0230.nii.gz'},
  {'image': './imagesTr/amos_0231.nii.gz',
   'label': './labelsTr/amos_0231.nii.gz'},
  {'image': './imagesTr/amos_0235.nii.gz',
   'label': './labelsTr/amos_0235.nii.gz'},
  {'image': './imagesTr/amos_0237.nii.gz',
   'label': './labelsTr/amos_0237.nii.gz'},
  {'image': './imagesTr/amos_0239.nii.gz',
   'label': './labelsTr/amos_0239.nii.gz'},
  {'image': './imagesTr/amos_0242.nii.gz',
   'label': './labelsTr/amos_0242.nii.gz'},
  {'image': './imagesTr/amos_0245.nii.gz',
   'label': './labelsTr/amos_0245.nii.gz'},
  {'image': './imagesTr/amos_0248.nii.gz',
   'label': './labelsTr/amos_0248.nii.gz'},
  {'image': './imagesTr/amos_0249.nii.gz',
   'label': './labelsTr/amos_0249.nii.gz'},
  {'image': './imagesTr/amos_0254.nii.gz',
   'label': './labelsTr/amos_0254.nii.gz'},
  {'image': './imagesTr/amos_0259.nii.gz',
   'label': './labelsTr/amos_0259.nii.gz'},
  {'image': './imagesTr/amos_0263.nii.gz',
   'label': './labelsTr/amos_0263.nii.gz'},
  {'image': './imagesTr/amos_0264.nii.gz',
   'label': './labelsTr/amos_0264.nii.gz'},
  {'image': './imagesTr/amos_0268.nii.gz',
   'label': './labelsTr/amos_0268.nii.gz'},
  {'image': './imagesTr/amos_0272.nii.gz',
   'label': './labelsTr/amos_0272.nii.gz'},
  {'image': './imagesTr/amos_0273.nii.gz',
   'label': './labelsTr/amos_0273.nii.gz'},
  {'image': './imagesTr/amos_0274.nii.gz',
   'label': './labelsTr/amos_0274.nii.gz'},
  {'image': './imagesTr/amos_0276.nii.gz',
   'label': './labelsTr/amos_0276.nii.gz'},
  {'image': './imagesTr/amos_0279.nii.gz',
   'label': './labelsTr/amos_0279.nii.gz'},
  {'image': './imagesTr/amos_0281.nii.gz',
   'label': './labelsTr/amos_0281.nii.gz'},
  {'image': './imagesTr/amos_0282.nii.gz',
   'label': './labelsTr/amos_0282.nii.gz'},
  {'image': './imagesTr/amos_0288.nii.gz',
   'label': './labelsTr/amos_0288.nii.gz'},
  {'image': './imagesTr/amos_0294.nii.gz',
   'label': './labelsTr/amos_0294.nii.gz'},
  {'image': './imagesTr/amos_0296.nii.gz',
   'label': './labelsTr/amos_0296.nii.gz'},
  {'image': './imagesTr/amos_0297.nii.gz',
   'label': './labelsTr/amos_0297.nii.gz'},
  {'image': './imagesTr/amos_0299.nii.gz',
   'label': './labelsTr/amos_0299.nii.gz'},
  {'image': './imagesTr/amos_0301.nii.gz',
   'label': './labelsTr/amos_0301.nii.gz'},
  {'image': './imagesTr/amos_0302.nii.gz',
   'label': './labelsTr/amos_0302.nii.gz'},
  {'image': './imagesTr/amos_0307.nii.gz',
   'label': './labelsTr/amos_0307.nii.gz'},
  {'image': './imagesTr/amos_0317.nii.gz',
   'label': './labelsTr/amos_0317.nii.gz'},
  {'image': './imagesTr/amos_0320.nii.gz',
   'label': './labelsTr/amos_0320.nii.gz'},
  {'image': './imagesTr/amos_0321.nii.gz',
   'label': './labelsTr/amos_0321.nii.gz'},
  {'image': './imagesTr/amos_0330.nii.gz',
   'label': './labelsTr/amos_0330.nii.gz'},
  {'image': './imagesTr/amos_0332.nii.gz',
   'label': './labelsTr/amos_0332.nii.gz'},
  {'image': './imagesTr/amos_0336.nii.gz',
   'label': './labelsTr/amos_0336.nii.gz'},
  {'image': './imagesTr/amos_0337.nii.gz',
   'label': './labelsTr/amos_0337.nii.gz'},
  {'image': './imagesTr/amos_0341.nii.gz',
   'label': './labelsTr/amos_0341.nii.gz'},
  {'image': './imagesTr/amos_0348.nii.gz',
   'label': './labelsTr/amos_0348.nii.gz'},
  {'image': './imagesTr/amos_0349.nii.gz',
   'label': './labelsTr/amos_0349.nii.gz'},
  {'image': './imagesTr/amos_0350.nii.gz',
   'label': './labelsTr/amos_0350.nii.gz'},
  {'image': './imagesTr/amos_0351.nii.gz',
   'label': './labelsTr/amos_0351.nii.gz'},
  {'image': './imagesTr/amos_0353.nii.gz',
   'label': './labelsTr/amos_0353.nii.gz'},
  {'image': './imagesTr/amos_0358.nii.gz',
   'label': './labelsTr/amos_0358.nii.gz'},
  {'image': './imagesTr/amos_0361.nii.gz',
   'label': './labelsTr/amos_0361.nii.gz'},
  {'image': './imagesTr/amos_0362.nii.gz',
   'label': './labelsTr/amos_0362.nii.gz'},
  {'image': './imagesTr/amos_0366.nii.gz',
   'label': './labelsTr/amos_0366.nii.gz'},
  {'image': './imagesTr/amos_0367.nii.gz',
   'label': './labelsTr/amos_0367.nii.gz'},
  {'image': './imagesTr/amos_0370.nii.gz',
   'label': './labelsTr/amos_0370.nii.gz'},
  {'image': './imagesTr/amos_0371.nii.gz',
   'label': './labelsTr/amos_0371.nii.gz'},
  {'image': './imagesTr/amos_0374.nii.gz',
   'label': './labelsTr/amos_0374.nii.gz'},
  {'image': './imagesTr/amos_0376.nii.gz',
   'label': './labelsTr/amos_0376.nii.gz'},
  {'image': './imagesTr/amos_0378.nii.gz',
   'label': './labelsTr/amos_0378.nii.gz'},
  {'image': './imagesTr/amos_0379.nii.gz',
   'label': './labelsTr/amos_0379.nii.gz'},
  {'image': './imagesTr/amos_0380.nii.gz',
   'label': './labelsTr/amos_0380.nii.gz'},
  {'image': './imagesTr/amos_0381.nii.gz',
   'label': './labelsTr/amos_0381.nii.gz'},
  {'image': './imagesTr/amos_0383.nii.gz',
   'label': './labelsTr/amos_0383.nii.gz'},
  {'image': './imagesTr/amos_0384.nii.gz',
   'label': './labelsTr/amos_0384.nii.gz'},
  {'image': './imagesTr/amos_0387.nii.gz',
   'label': './labelsTr/amos_0387.nii.gz'},
  {'image': './imagesTr/amos_0388.nii.gz',
   'label': './labelsTr/amos_0388.nii.gz'},
  {'image': './imagesTr/amos_0390.nii.gz',
   'label': './labelsTr/amos_0390.nii.gz'},
  {'image': './imagesTr/amos_0391.nii.gz',
   'label': './labelsTr/amos_0391.nii.gz'},
  {'image': './imagesTr/amos_0392.nii.gz',
   'label': './labelsTr/amos_0392.nii.gz'},
  {'image': './imagesTr/amos_0395.nii.gz',
   'label': './labelsTr/amos_0395.nii.gz'},
  {'image': './imagesTr/amos_0396.nii.gz',
   'label': './labelsTr/amos_0396.nii.gz'},
  {'image': './imagesTr/amos_0398.nii.gz',
   'label': './labelsTr/amos_0398.nii.gz'},
  {'image': './imagesTr/amos_0400.nii.gz',
   'label': './labelsTr/amos_0400.nii.gz'},
  {'image': './imagesTr/amos_0401.nii.gz',
   'label': './labelsTr/amos_0401.nii.gz'},
  {'image': './imagesTr/amos_0402.nii.gz',
   'label': './labelsTr/amos_0402.nii.gz'},
  {'image': './imagesTr/amos_0403.nii.gz',
   'label': './labelsTr/amos_0403.nii.gz'},
  {'image': './imagesTr/amos_0404.nii.gz',
   'label': './labelsTr/amos_0404.nii.gz'},
  {'image': './imagesTr/amos_0405.nii.gz',
   'label': './labelsTr/amos_0405.nii.gz'},
  {'image': './imagesTr/amos_0406.nii.gz',
   'label': './labelsTr/amos_0406.nii.gz'},
  {'image': './imagesTr/amos_0408.nii.gz',
   'label': './labelsTr/amos_0408.nii.gz'},
  {'image': './imagesTr/amos_0410.nii.gz',
   'label': './labelsTr/amos_0410.nii.gz'},
  {'image': './imagesTr/amos_0507.nii.gz',
   'label': './labelsTr/amos_0507.nii.gz'},
  {'image': './imagesTr/amos_0508.nii.gz',
   'label': './labelsTr/amos_0508.nii.gz'},
  {'image': './imagesTr/amos_0510.nii.gz',
   'label': './labelsTr/amos_0510.nii.gz'},
  {'image': './imagesTr/amos_0514.nii.gz',
   'label': './labelsTr/amos_0514.nii.gz'},
  {'image': './imagesTr/amos_0517.nii.gz',
   'label': './labelsTr/amos_0517.nii.gz'},
  {'image': './imagesTr/amos_0518.nii.gz',
   'label': './labelsTr/amos_0518.nii.gz'},
  {'image': './imagesTr/amos_0522.nii.gz',
   'label': './labelsTr/amos_0522.nii.gz'},
  {'image': './imagesTr/amos_0530.nii.gz',
   'label': './labelsTr/amos_0530.nii.gz'},
  {'image': './imagesTr/amos_0532.nii.gz',
   'label': './labelsTr/amos_0532.nii.gz'},
  {'image': './imagesTr/amos_0538.nii.gz',
   'label': './labelsTr/amos_0538.nii.gz'},
  {'image': './imagesTr/amos_0540.nii.gz',
   'label': './labelsTr/amos_0540.nii.gz'},
  {'image': './imagesTr/amos_0541.nii.gz',
   'label': './labelsTr/amos_0541.nii.gz'},
  {'image': './imagesTr/amos_0548.nii.gz',
   'label': './labelsTr/amos_0548.nii.gz'},
  {'image': './imagesTr/amos_0551.nii.gz',
   'label': './labelsTr/amos_0551.nii.gz'},
  {'image': './imagesTr/amos_0554.nii.gz',
   'label': './labelsTr/amos_0554.nii.gz'},
  {'image': './imagesTr/amos_0555.nii.gz',
   'label': './labelsTr/amos_0555.nii.gz'},
  {'image': './imagesTr/amos_0557.nii.gz',
   'label': './labelsTr/amos_0557.nii.gz'},
  {'image': './imagesTr/amos_0558.nii.gz',
   'label': './labelsTr/amos_0558.nii.gz'},
  {'image': './imagesTr/amos_0570.nii.gz',
   'label': './labelsTr/amos_0570.nii.gz'},
  {'image': './imagesTr/amos_0571.nii.gz',
   'label': './labelsTr/amos_0571.nii.gz'},
  {'image': './imagesTr/amos_0578.nii.gz',

In [39]:
labels = dataset["labels"]
labels = ", ".join([v for k, v in labels.items() if v != "background"])
print(labels)

spleen, right kidney, left kidney, gall bladder, esophagus, liver, stomach, arota, postcava, pancreas, right
adrenal gland, left adrenal gland, duodenum, bladder, prostate/uterus

In [41]:
def map_roinames(row):
    if row["file_type"] == "mask":
        return labels
    else:
        return ""

index_df["ROINames"] = index_df.apply(map_roinames, axis=1)
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality,BodyPartExamined,ROINames
0,Tr,1,amos22/imagesTr/amos_0001.nii.gz,scan,Tr_1,MedImage,7afee8a38d53124559a13a6781f122286d3430f7,"(768, 768, 90)",3,53084160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,
1,Tr,4,amos22/imagesTr/amos_0004.nii.gz,scan,Tr_4,MedImage,c30d47e4286bcdfd0de0e7a91f2c83fdbf5f6c73,"(512, 512, 78)",3,20447232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,
2,Tr,5,amos22/imagesTr/amos_0005.nii.gz,scan,Tr_5,MedImage,291404b6eca6b90014134fc09166a5b0c67d0191,"(768, 768, 80)",3,47185920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,
3,Tr,6,amos22/imagesTr/amos_0006.nii.gz,scan,Tr_6,MedImage,a0dbfbc847622c27f8379106bd829d64bd77d77c,"(512, 512, 99)",3,25952256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,
4,Tr,7,amos22/imagesTr/amos_0007.nii.gz,scan,Tr_7,MedImage,ca96ae6008c490bdc46ab0f89474e7e03ce6217b,"(768, 768, 107)",3,63111168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,Va,573,amos22/labelsVa/amos_0573.nii.gz,mask,Va_573,Mask,f2333983065ac98b2a71b1457951aea05d3315db,"(320, 260, 72)",3,5990400,...,1.157307,1.728001,74.748770,70213.070716,"(113.01956759593764, 130.79836259630235, 226.0...",3.0,amos22/imagesVa/amos_0573.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
956,Va,575,amos22/labelsVa/amos_0575.nii.gz,mask,Va_575,Mask,3db4550bfed09c738dc7b18012dc2d7e0f455799,"(260, 144, 320)",3,11980800,...,1.387391,1.378596,90.089618,101990.413850,"(130.14465587173495, 180.56158393522423, 248.9...",3.0,amos22/imagesVa/amos_0575.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
957,Va,576,amos22/labelsVa/amos_0576.nii.gz,mask,Va_576,Mask,17f722934f527aa4b4d8548d7117eb6c7b85e1a8,"(320, 260, 72)",3,5990400,...,1.168343,1.550508,84.699301,90150.784847,"(131.93846318752645, 154.14944500519806, 239.0...",13.0,amos22/imagesVa/amos_0576.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
958,Va,581,amos22/labelsVa/amos_0581.nii.gz,mask,Va_581,Mask,56423d0ec2e8d532cacbfccf0ca743e2650b96a2,"(576, 468, 72)",3,19408896,...,1.336116,1.461998,85.326695,91491.281922,"(123.94713972021772, 165.60775457070784, 242.1...",2.0,amos22/imagesVa/amos_0581.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
959,Va,598,amos22/labelsVa/amos_0598.nii.gz,mask,Va_598,Mask,cfdeb7dd13d9c8eef39ab4b5a760b635c69ac3f3,"(260, 144, 320)",3,11980800,...,1.781415,1.236302,76.943835,74397.359546,"(97.57059311170033, 173.81370215980712, 214.88...",6.0,amos22/imagesVa/amos_0598.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."

In [42]:
index_df.to_csv(indexed_datasets.imgtools_path / "AMOS" / "index.csv", index=False)

In [1]:
from imgnet.collections.store import IndexedDatasets

indexed_datasets = IndexedDatasets()

/home/gpudual/bhklab/josh/med-image_index/.pixi/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
14:34:03 [info     ] Indexed datasets path: /home/gpudual/.local/share/med-imagenet/indexed_datasets [imgnet] call=store.__init__:67

In [2]:
from imgindex.model import validate_index

index = indexed_datasets.index("AMOS")
validate_index(index, "nifti", lazy=True)

Invalid NIFTI index: {
    "SCHEMA": {
        "COLUMN_NOT_IN_DATAFRAME": [
            {
                "schema": "NiftiIndex",
                "column": "NiftiIndex",
                "check": "column_in_dataframe",
                "error": "column 'SampleID' not in dataframe. Columns in dataframe: ['Split', 'ImageID', 'filepath', 'file_type', 'reference_id', 'class', 'hash', 'size', 'ndim', 'nvoxels', 'spacing', 'origin', 'direction', 'min', 'max', 'sum', 'mean', 'std', 'variance', 'dtype_str', 'dtype_numpy', 'mask.bbox.size', 'mask.bbox.min_coord', 'mask.bbox.max_coord', 'mask.feret_diameter', 'mask.roundness', 'mask.flatness', 'mask.elongation', 'mask.equivalent_spherical_radius', 'mask.equivalent_spherical_perimeter', 'mask.equivalent_ellipsoid_diameters', 'mask.volume_count', 'reference_scan', 'Modality', 'BodyPartExamined', 'ROINames']"
            }
        ]
    }
}

In [3]:
index.rename(columns={"reference_id": "SampleID"}, inplace=True)

In [4]:
validate_index(index, "nifti", lazy=True)

,Split,ImageID,filepath,file_type,SampleID,class,hash,size,ndim,nvoxels,...,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality,BodyPartExamined,ROINames
0,Tr,1,amos22/imagesTr/amos_0001.nii.gz,scan,Tr_1,MedImage,7afee8a38d53124559a13a6781f122286d3430f7,"(768, 768, 90)",3,53084160,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,NaN
1,Tr,4,amos22/imagesTr/amos_0004.nii.gz,scan,Tr_4,MedImage,c30d47e4286bcdfd0de0e7a91f2c83fdbf5f6c73,"(512, 512, 78)",3,20447232,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,NaN
2,Tr,5,amos22/imagesTr/amos_0005.nii.gz,scan,Tr_5,MedImage,291404b6eca6b90014134fc09166a5b0c67d0191,"(768, 768, 80)",3,47185920,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,NaN
3,Tr,6,amos22/imagesTr/amos_0006.nii.gz,scan,Tr_6,MedImage,a0dbfbc847622c27f8379106bd829d64bd77d77c,"(512, 512, 99)",3,25952256,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,NaN
4,Tr,7,amos22/imagesTr/amos_0007.nii.gz,scan,Tr_7,MedImage,ca96ae6008c490bdc46ab0f89474e7e03ce6217b,"(768, 768, 107)",3,63111168,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,ABDOMEN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
955,Va,573,amos22/labelsVa/amos_0573.nii.gz,mask,Va_573,Mask,f2333983065ac98b2a71b1457951aea05d3315db,"(320, 260, 72)",3,5990400,...,1.157307,1.728001,74.748770,70213.070716,"(113.01956759593764, 130.79836259630235, 226.0...",3.0,amos22/imagesVa/amos_0573.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
956,Va,575,amos22/labelsVa/amos_0575.nii.gz,mask,Va_575,Mask,3db4550bfed09c738dc7b18012dc2d7e0f455799,"(260, 144, 320)",3,11980800,...,1.387391,1.378596,90.089618,101990.413850,"(130.14465587173495, 180.56158393522423, 248.9...",3.0,amos22/imagesVa/amos_0575.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
957,Va,576,amos22/labelsVa/amos_0576.nii.gz,mask,Va_576,Mask,17f722934f527aa4b4d8548d7117eb6c7b85e1a8,"(320, 260, 72)",3,5990400,...,1.168343,1.550508,84.699301,90150.784847,"(131.93846318752645, 154.14944500519806, 239.0...",13.0,amos22/imagesVa/amos_0576.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
958,Va,581,amos22/labelsVa/amos_0581.nii.gz,mask,Va_581,Mask,56423d0ec2e8d532cacbfccf0ca743e2650b96a2,"(576, 468, 72)",3,19408896,...,1.336116,1.461998,85.326695,91491.281922,"(123.94713972021772, 165.60775457070784, 242.1...",2.0,amos22/imagesVa/amos_0581.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."
959,Va,598,amos22/labelsVa/amos_0598.nii.gz,mask,Va_598,Mask,cfdeb7dd13d9c8eef39ab4b5a760b635c69ac3f3,"(260, 144, 320)",3,11980800,...,1.781415,1.236302,76.943835,74397.359546,"(97.57059311170033, 173.81370215980712, 214.88...",6.0,amos22/imagesVa/amos_0598.nii.gz,SEG,ABDOMEN,"spleen, right kidney, left kidney, gall bladde..."

In [5]:
from pathlib import Path

new_index_dir = Path("/home/gpudual/bhklab/josh/med-image_index/new_index")
collection_path = new_index_dir / "AMOS"
collection_path.mkdir(parents=True, exist_ok=True)

index.to_csv(collection_path / "index.csv", index=False)

In [6]:
import json
source = indexed_datasets.source_config("AMOS")

with open(collection_path / "source.json", "w") as f:
    json.dump(source.model_dump(mode="json"), f, indent=2)