In [1]:
import json
from pathlib import Path
from imgnet.collections.store import IndexedDatasets
from imgnet.collections.source import HuggingFaceSource
from imgnet.download import download_collection
from imgtools.nifti.crawl import Crawler
from rich import print

/home/gpudual/bhklab/josh/med-image_index/.pixi/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
indexed_datasets = IndexedDatasets("indexed_datasets") # This will download the latest version of the indexed_datasets if you dont provide a path
print(indexed_datasets.collections[:10])

15:07:17 [info     ] Indexed datasets path: /home/gpudual/bhklab/josh/med-image_index/notebooks/indexed_datasets [imgnet] call=store.__init__:47

[
    '4D-Lung',
    'ACRIN-6698',
    'ACRIN-Contralateral-Breast-MR',
    'ACRIN-FLT-Breast',
    'ACRIN-NSCLC-FDG-PET',
    'Adrenal-ACC-Ki67-Seg',
    'Advanced-MRI-Breast-Lesions',
    'Anti-PD-1_Lung',
    'B-mode-and-CEUS-Liver',
    'BREAST-DIAGNOSIS'
]

In [3]:
source = HuggingFaceSource(
    source="huggingface",
    repo_id="zhaodongwu/MSWAL",
    file_type="nifti",
    description="MSWAL comprises 694 high-resolution CT scans (191,417 slices) with 7 lesion types (e.g., liver tumors, kidney stones), balanced gender distribution (53.9% male, 46.1% female), and diverse CT contrast phases (non-contrast, arterial, venous, etc.), offering a fully annotated, multi-class dataset for precise abdominal lesion segmentation."
)

In [4]:
dataset_index_path = (indexed_datasets.imgtools_path / "MSWAL")
dataset_index_path.mkdir(parents=True, exist_ok=True)
with open(dataset_index_path / "source.json", "w") as f:
    json.dump(source.model_dump(mode="json"), f, indent=2)

In [5]:
print(indexed_datasets.source_config("MSWAL"))

HuggingFaceSource(
    file_type=<FileType.NIFTI: 'nifti'>,
    source='huggingface',
    repo_id='zhaodongwu/MSWAL',
    post_download=['unzip'],
    description='MSWAL comprises 694 high-resolution CT scans (191,417 slices) with 7 lesion types (e.g., liver
tumors, kidney stones), balanced gender distribution (53.9% male, 46.1% female), and diverse CT contrast phases
(non-contrast, arterial, venous, etc.), offering a fully annotated, multi-class dataset for precise abdominal
lesion segmentation.'
)

In [6]:
temp_data_path = Path("temp_data") / "MSWAL"
temp_data_path.mkdir(parents=True, exist_ok=True)
download_collection(temp_data_path, source)

Fetching 970 files: 100%|██████████| 970/970 [07:15<00:00,  2.23it/s]

In [10]:
import imgtools.loggers
import logging

imgtools.loggers.get_logger("imgtools").setLevel(logging.INFO)

crawler = Crawler(
    nifti_dir=temp_data_path,
    scan_name_pattern="images{Split}/MSWAL_{ImageID:d}_0000.nii.gz",
    mask_name_pattern="labels{Split}/MSWAL_{ImageID:d}.nii.gz",
    output_dir=indexed_datasets.imgtools_path,
    n_jobs=10,
    force=True,
    deep=True,
)
crawler.crawl()

15:20:07 [info     ] Starting NIFTI crawl.          [imgtools] nifti_dir=PosixPath('temp_data/MSWAL') output_dir=PosixPath('indexed_datasets/.imgtools') dataset_name=None call=crawler.crawl:78
         [info     ] Found 968 NIfTI files in /home/gpudual/bhklab/josh/med-image_index/notebooks/temp_data/MSWAL. [imgtools] call=parse_niftis.parse_nifti_dir:426
         [info     ] Using shared keys: ['Split', 'ImageID'] for reference_id, this will be used to link masks to their referenced scans [imgtools] call=parse_niftis.parse_nifti_dir:447
15:27:54 [info     ] Parsing all NIfTI files took 467.5426 seconds [imgtools] call=timer_utils.__exit__:58
         [info     ] Saved index.                   [imgtools] path=indexed_datasets/.imgtools/MSWAL/index.csv rows=968 call=parse_niftis.parse_nifti_dir:492

In [12]:
index_df = indexed_datasets.index("MSWAL")
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.bbox.max_coord,mask.feret_diameter,mask.roundness,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan
0,Tr,1,imagesTr/MSWAL_0001_0000.nii.gz,scan,Tr_1,MedImage,ec117e20f6d9e39b42bfcb5988e821eb1a066165,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tr,2,imagesTr/MSWAL_0002_0000.nii.gz,scan,Tr_2,MedImage,5041b6c35a82c0fea483e97460b690d66087ab6e,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Tr,3,imagesTr/MSWAL_0003_0000.nii.gz,scan,Tr_3,MedImage,67cb8cf2c2c31e405099da93f5b0f4fc56856744,"(512, 512, 381)",3,99876864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Tr,8,imagesTr/MSWAL_0008_0000.nii.gz,scan,Tr_8,MedImage,f716e03e231ad3e07b4adfc28ea701cab38842ee,"(512, 512, 201)",3,52690944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Tr,9,imagesTr/MSWAL_0009_0000.nii.gz,scan,Tr_9,MedImage,d75e77b78dc96498200fd8c59de83d4e7c168989,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,Tr,688,labelsTr/MSWAL_0688.nii.gz,mask,Tr_688,Mask,6e87ecb0b91396de2aa79ac5a2a83955f1fe7f42,"(512, 512, 474)",3,124256256,...,"(378, 346, 340)",248.788027,0.393446,2.486319,2.196475,13.487813,2286.087942,"(11.307281870773021, 28.113509098844226, 61.75...",22.0,imagesTr/MSWAL_0688_0000.nii.gz
964,Tr,690,labelsTr/MSWAL_0690.nii.gz,mask,Tr_690,Mask,b9aa4bf64397d62bffd687ebf23ac35765441b26,"(512, 512, 523)",3,137101312,...,"(344, 297, 353)",238.822051,0.685153,1.451475,1.785663,43.438991,23712.062073,"(55.860323267234016, 81.07988364160474, 144.78...",20.0,imagesTr/MSWAL_0690_0000.nii.gz
965,Tr,692,labelsTr/MSWAL_0692.nii.gz,mask,Tr_692,Mask,20ebed3cc05afe10a9e268c3ace9d45a3ae3e5c0,"(512, 512, 293)",3,76808192,...,"(379, 285, 260)",64.382698,0.480680,1.843109,1.619462,15.214846,2909.008483,"(17.2374613949725, 31.770517222565385, 51.4511...",3.0,imagesTr/MSWAL_0692_0000.nii.gz
966,Tr,693,labelsTr/MSWAL_0693.nii.gz,mask,Tr_693,Mask,c357b6330f01eadd8ceb0d4f2a33d73603169e38,"(512, 512, 240)",3,62914560,...,"(194, 306, 238)",147.898405,0.622786,4.158035,2.385840,10.546019,1397.613227,"(6.104443010089622, 25.382488557742494, 60.558...",7.0,imagesTr/MSWAL_0693_0000.nii.gz
967,Tr,694,labelsTr/MSWAL_0694.nii.gz,mask,Tr_694,Mask,d050aef1c1a4642607a55f5da6de4f5502d006ad,"(512, 512, 276)",3,72351744,...,"(323, 279, 176)",9.028614,0.915197,1.405936,1.271195,3.579363,160.998309,"(5.265681523245576, 7.403213210767661, 9.41092...",1.0,imagesTr/MSWAL_0694_0000.nii.gz

In [24]:
def map_modality(row):
    if row["file_type"] == "scan":
        return "CT"
    elif row["file_type"] == "mask":
        return "SEG"

index_df["Modality"] = index_df.apply(map_modality, axis=1)
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.feret_diameter,mask.roundness,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality
0,Tr,1,imagesTr/MSWAL_0001_0000.nii.gz,scan,Tr_1,MedImage,ec117e20f6d9e39b42bfcb5988e821eb1a066165,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
1,Tr,2,imagesTr/MSWAL_0002_0000.nii.gz,scan,Tr_2,MedImage,5041b6c35a82c0fea483e97460b690d66087ab6e,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
2,Tr,3,imagesTr/MSWAL_0003_0000.nii.gz,scan,Tr_3,MedImage,67cb8cf2c2c31e405099da93f5b0f4fc56856744,"(512, 512, 381)",3,99876864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
3,Tr,8,imagesTr/MSWAL_0008_0000.nii.gz,scan,Tr_8,MedImage,f716e03e231ad3e07b4adfc28ea701cab38842ee,"(512, 512, 201)",3,52690944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
4,Tr,9,imagesTr/MSWAL_0009_0000.nii.gz,scan,Tr_9,MedImage,d75e77b78dc96498200fd8c59de83d4e7c168989,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,Tr,688,labelsTr/MSWAL_0688.nii.gz,mask,Tr_688,Mask,6e87ecb0b91396de2aa79ac5a2a83955f1fe7f42,"(512, 512, 474)",3,124256256,...,248.788027,0.393446,2.486319,2.196475,13.487813,2286.087942,"(11.307281870773021, 28.113509098844226, 61.75...",22.0,imagesTr/MSWAL_0688_0000.nii.gz,SEG
964,Tr,690,labelsTr/MSWAL_0690.nii.gz,mask,Tr_690,Mask,b9aa4bf64397d62bffd687ebf23ac35765441b26,"(512, 512, 523)",3,137101312,...,238.822051,0.685153,1.451475,1.785663,43.438991,23712.062073,"(55.860323267234016, 81.07988364160474, 144.78...",20.0,imagesTr/MSWAL_0690_0000.nii.gz,SEG
965,Tr,692,labelsTr/MSWAL_0692.nii.gz,mask,Tr_692,Mask,20ebed3cc05afe10a9e268c3ace9d45a3ae3e5c0,"(512, 512, 293)",3,76808192,...,64.382698,0.480680,1.843109,1.619462,15.214846,2909.008483,"(17.2374613949725, 31.770517222565385, 51.4511...",3.0,imagesTr/MSWAL_0692_0000.nii.gz,SEG
966,Tr,693,labelsTr/MSWAL_0693.nii.gz,mask,Tr_693,Mask,c357b6330f01eadd8ceb0d4f2a33d73603169e38,"(512, 512, 240)",3,62914560,...,147.898405,0.622786,4.158035,2.385840,10.546019,1397.613227,"(6.104443010089622, 25.382488557742494, 60.558...",7.0,imagesTr/MSWAL_0693_0000.nii.gz,SEG
967,Tr,694,labelsTr/MSWAL_0694.nii.gz,mask,Tr_694,Mask,d050aef1c1a4642607a55f5da6de4f5502d006ad,"(512, 512, 276)",3,72351744,...,9.028614,0.915197,1.405936,1.271195,3.579363,160.998309,"(5.265681523245576, 7.403213210767661, 9.41092...",1.0,imagesTr/MSWAL_0694_0000.nii.gz,SEG

In [25]:
index_df["BodyPartExamined"] = "Abdomen"
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.roundness,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality,BodyPartExamined
0,Tr,1,imagesTr/MSWAL_0001_0000.nii.gz,scan,Tr_1,MedImage,ec117e20f6d9e39b42bfcb5988e821eb1a066165,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen
1,Tr,2,imagesTr/MSWAL_0002_0000.nii.gz,scan,Tr_2,MedImage,5041b6c35a82c0fea483e97460b690d66087ab6e,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen
2,Tr,3,imagesTr/MSWAL_0003_0000.nii.gz,scan,Tr_3,MedImage,67cb8cf2c2c31e405099da93f5b0f4fc56856744,"(512, 512, 381)",3,99876864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen
3,Tr,8,imagesTr/MSWAL_0008_0000.nii.gz,scan,Tr_8,MedImage,f716e03e231ad3e07b4adfc28ea701cab38842ee,"(512, 512, 201)",3,52690944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen
4,Tr,9,imagesTr/MSWAL_0009_0000.nii.gz,scan,Tr_9,MedImage,d75e77b78dc96498200fd8c59de83d4e7c168989,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,Tr,688,labelsTr/MSWAL_0688.nii.gz,mask,Tr_688,Mask,6e87ecb0b91396de2aa79ac5a2a83955f1fe7f42,"(512, 512, 474)",3,124256256,...,0.393446,2.486319,2.196475,13.487813,2286.087942,"(11.307281870773021, 28.113509098844226, 61.75...",22.0,imagesTr/MSWAL_0688_0000.nii.gz,SEG,Abdomen
964,Tr,690,labelsTr/MSWAL_0690.nii.gz,mask,Tr_690,Mask,b9aa4bf64397d62bffd687ebf23ac35765441b26,"(512, 512, 523)",3,137101312,...,0.685153,1.451475,1.785663,43.438991,23712.062073,"(55.860323267234016, 81.07988364160474, 144.78...",20.0,imagesTr/MSWAL_0690_0000.nii.gz,SEG,Abdomen
965,Tr,692,labelsTr/MSWAL_0692.nii.gz,mask,Tr_692,Mask,20ebed3cc05afe10a9e268c3ace9d45a3ae3e5c0,"(512, 512, 293)",3,76808192,...,0.480680,1.843109,1.619462,15.214846,2909.008483,"(17.2374613949725, 31.770517222565385, 51.4511...",3.0,imagesTr/MSWAL_0692_0000.nii.gz,SEG,Abdomen
966,Tr,693,labelsTr/MSWAL_0693.nii.gz,mask,Tr_693,Mask,c357b6330f01eadd8ceb0d4f2a33d73603169e38,"(512, 512, 240)",3,62914560,...,0.622786,4.158035,2.385840,10.546019,1397.613227,"(6.104443010089622, 25.382488557742494, 60.558...",7.0,imagesTr/MSWAL_0693_0000.nii.gz,SEG,Abdomen
967,Tr,694,labelsTr/MSWAL_0694.nii.gz,mask,Tr_694,Mask,d050aef1c1a4642607a55f5da6de4f5502d006ad,"(512, 512, 276)",3,72351744,...,0.915197,1.405936,1.271195,3.579363,160.998309,"(5.265681523245576, 7.403213210767661, 9.41092...",1.0,imagesTr/MSWAL_0694_0000.nii.gz,SEG,Abdomen

In [14]:
import json

dataset_json = temp_data_path / "dataset.json"
with open(dataset_json, "r") as f:
    dataset = json.load(f)

dataset

{'name': 'MSWAL',
 'description': ' 3D Multi-class Segmentation of Whole Abdominal Lesions Dataset',
 'licence': 'CC BY-NC 4.0',
 'relase': 'July 8, 2025',
 'tensorImageSize': '3D',
 'file_ending': '.nii.gz',
 'channel_names': {'0': 'CT'},
 'labels': {'background': 0,
  'gallstone': 1,
  'kidney stone': 2,
  'liver tumor': 3,
  'kidney tumor': 4,
  'pancreatic cancer': 5,
  'liver cyst': 6,
  'kidney cyst': 7},
 'numTraining': 484,
 'numTest': 210,
 'training': [{'image': './imagesTr/MSWAL_0001_0000.nii.gz',
   'label': './labelsTr/MSWAL_0001.nii.gz'},
  {'image': './imagesTr/MSWAL_0002_0000.nii.gz',
   'label': './labelsTr/MSWAL_0002.nii.gz'},
  {'image': './imagesTr/MSWAL_0003_0000.nii.gz',
   'label': './labelsTr/MSWAL_0003.nii.gz'},
  {'image': './imagesTr/MSWAL_0008_0000.nii.gz',
   'label': './labelsTr/MSWAL_0008.nii.gz'},
  {'image': './imagesTr/MSWAL_0009_0000.nii.gz',
   'label': './labelsTr/MSWAL_0009.nii.gz'},
  {'image': './imagesTr/MSWAL_0011_0000.nii.gz',
   'label': './labelsTr/MSWAL_0011.nii.gz'},
  {'image': './imagesTr/MSWAL_0013_0000.nii.gz',
   'label': './labelsTr/MSWAL_0013.nii.gz'},
  {'image': './imagesTr/MSWAL_0014_0000.nii.gz',
   'label': './labelsTr/MSWAL_0014.nii.gz'},
  {'image': './imagesTr/MSWAL_0015_0000.nii.gz',
   'label': './labelsTr/MSWAL_0015.nii.gz'},
  {'image': './imagesTr/MSWAL_0017_0000.nii.gz',
   'label': './labelsTr/MSWAL_0017.nii.gz'},
  {'image': './imagesTr/MSWAL_0018_0000.nii.gz',
   'label': './labelsTr/MSWAL_0018.nii.gz'},
  {'image': './imagesTr/MSWAL_0020_0000.nii.gz',
   'label': './labelsTr/MSWAL_0020.nii.gz'},
  {'image': './imagesTr/MSWAL_0021_0000.nii.gz',
   'label': './labelsTr/MSWAL_0021.nii.gz'},
  {'image': './imagesTr/MSWAL_0022_0000.nii.gz',
   'label': './labelsTr/MSWAL_0022.nii.gz'},
  {'image': './imagesTr/MSWAL_0024_0000.nii.gz',
   'label': './labelsTr/MSWAL_0024.nii.gz'},
  {'image': './imagesTr/MSWAL_0026_0000.nii.gz',
   'label': './labelsTr/MSWAL_0026.nii.gz'},
  {'image': './imagesTr/MSWAL_0027_0000.nii.gz',
   'label': './labelsTr/MSWAL_0027.nii.gz'},
  {'image': './imagesTr/MSWAL_0028_0000.nii.gz',
   'label': './labelsTr/MSWAL_0028.nii.gz'},
  {'image': './imagesTr/MSWAL_0029_0000.nii.gz',
   'label': './labelsTr/MSWAL_0029.nii.gz'},
  {'image': './imagesTr/MSWAL_0031_0000.nii.gz',
   'label': './labelsTr/MSWAL_0031.nii.gz'},
  {'image': './imagesTr/MSWAL_0032_0000.nii.gz',
   'label': './labelsTr/MSWAL_0032.nii.gz'},
  {'image': './imagesTr/MSWAL_0033_0000.nii.gz',
   'label': './labelsTr/MSWAL_0033.nii.gz'},
  {'image': './imagesTr/MSWAL_0034_0000.nii.gz',
   'label': './labelsTr/MSWAL_0034.nii.gz'},
  {'image': './imagesTr/MSWAL_0035_0000.nii.gz',
   'label': './labelsTr/MSWAL_0035.nii.gz'},
  {'image': './imagesTr/MSWAL_0037_0000.nii.gz',
   'label': './labelsTr/MSWAL_0037.nii.gz'},
  {'image': './imagesTr/MSWAL_0038_0000.nii.gz',
   'label': './labelsTr/MSWAL_0038.nii.gz'},
  {'image': './imagesTr/MSWAL_0039_0000.nii.gz',
   'label': './labelsTr/MSWAL_0039.nii.gz'},
  {'image': './imagesTr/MSWAL_0040_0000.nii.gz',
   'label': './labelsTr/MSWAL_0040.nii.gz'},
  {'image': './imagesTr/MSWAL_0041_0000.nii.gz',
   'label': './labelsTr/MSWAL_0041.nii.gz'},
  {'image': './imagesTr/MSWAL_0042_0000.nii.gz',
   'label': './labelsTr/MSWAL_0042.nii.gz'},
  {'image': './imagesTr/MSWAL_0045_0000.nii.gz',
   'label': './labelsTr/MSWAL_0045.nii.gz'},
  {'image': './imagesTr/MSWAL_0046_0000.nii.gz',
   'label': './labelsTr/MSWAL_0046.nii.gz'},
  {'image': './imagesTr/MSWAL_0049_0000.nii.gz',
   'label': './labelsTr/MSWAL_0049.nii.gz'},
  {'image': './imagesTr/MSWAL_0050_0000.nii.gz',
   'label': './labelsTr/MSWAL_0050.nii.gz'},
  {'image': './imagesTr/MSWAL_0051_0000.nii.gz',
   'label': './labelsTr/MSWAL_0051.nii.gz'},
  {'image': './imagesTr/MSWAL_0052_0000.nii.gz',
   'label': './labelsTr/MSWAL_0052.nii.gz'},
  {'image': './imagesTr/MSWAL_0054_0000.nii.gz',
   'label': './labelsTr/MSWAL_0054.nii.gz'},
  {'image': './imagesTr/MSWAL_0055_0000.nii.gz',
   'label': './labelsTr/MSWAL_0055.nii.gz'},
  {'image': './imagesTr/MSWAL_0056_0000.nii.gz',
   'label': './labelsTr/MSWAL_0056.nii.gz'},
  {'image': './imagesTr/MSWAL_0057_0000.nii.gz',
   'label': './labelsTr/MSWAL_0057.nii.gz'},
  {'image': './imagesTr/MSWAL_0059_0000.nii.gz',
   'label': './labelsTr/MSWAL_0059.nii.gz'},
  {'image': './imagesTr/MSWAL_0060_0000.nii.gz',
   'label': './labelsTr/MSWAL_0060.nii.gz'},
  {'image': './imagesTr/MSWAL_0061_0000.nii.gz',
   'label': './labelsTr/MSWAL_0061.nii.gz'},
  {'image': './imagesTr/MSWAL_0063_0000.nii.gz',
   'label': './labelsTr/MSWAL_0063.nii.gz'},
  {'image': './imagesTr/MSWAL_0064_0000.nii.gz',
   'label': './labelsTr/MSWAL_0064.nii.gz'},
  {'image': './imagesTr/MSWAL_0065_0000.nii.gz',
   'label': './labelsTr/MSWAL_0065.nii.gz'},
  {'image': './imagesTr/MSWAL_0066_0000.nii.gz',
   'label': './labelsTr/MSWAL_0066.nii.gz'},
  {'image': './imagesTr/MSWAL_0067_0000.nii.gz',
   'label': './labelsTr/MSWAL_0067.nii.gz'},
  {'image': './imagesTr/MSWAL_0069_0000.nii.gz',
   'label': './labelsTr/MSWAL_0069.nii.gz'},
  {'image': './imagesTr/MSWAL_0072_0000.nii.gz',
   'label': './labelsTr/MSWAL_0072.nii.gz'},
  {'image': './imagesTr/MSWAL_0075_0000.nii.gz',
   'label': './labelsTr/MSWAL_0075.nii.gz'},
  {'image': './imagesTr/MSWAL_0077_0000.nii.gz',
   'label': './labelsTr/MSWAL_0077.nii.gz'},
  {'image': './imagesTr/MSWAL_0080_0000.nii.gz',
   'label': './labelsTr/MSWAL_0080.nii.gz'},
  {'image': './imagesTr/MSWAL_0082_0000.nii.gz',
   'label': './labelsTr/MSWAL_0082.nii.gz'},
  {'image': './imagesTr/MSWAL_0083_0000.nii.gz',
   'label': './labelsTr/MSWAL_0083.nii.gz'},
  {'image': './imagesTr/MSWAL_0084_0000.nii.gz',
   'label': './labelsTr/MSWAL_0084.nii.gz'},
  {'image': './imagesTr/MSWAL_0085_0000.nii.gz',
   'label': './labelsTr/MSWAL_0085.nii.gz'},
  {'image': './imagesTr/MSWAL_0086_0000.nii.gz',
   'label': './labelsTr/MSWAL_0086.nii.gz'},
  {'image': './imagesTr/MSWAL_0088_0000.nii.gz',
   'label': './labelsTr/MSWAL_0088.nii.gz'},
  {'image': './imagesTr/MSWAL_0089_0000.nii.gz',
   'label': './labelsTr/MSWAL_0089.nii.gz'},
  {'image': './imagesTr/MSWAL_0092_0000.nii.gz',
   'label': './labelsTr/MSWAL_0092.nii.gz'},
  {'image': './imagesTr/MSWAL_0093_0000.nii.gz',
   'label': './labelsTr/MSWAL_0093.nii.gz'},
  {'image': './imagesTr/MSWAL_0094_0000.nii.gz',
   'label': './labelsTr/MSWAL_0094.nii.gz'},
  {'image': './imagesTr/MSWAL_0095_0000.nii.gz',
   'label': './labelsTr/MSWAL_0095.nii.gz'},
  {'image': './imagesTr/MSWAL_0096_0000.nii.gz',
   'label': './labelsTr/MSWAL_0096.nii.gz'},
  {'image': './imagesTr/MSWAL_0098_0000.nii.gz',
   'label': './labelsTr/MSWAL_0098.nii.gz'},
  {'image': './imagesTr/MSWAL_0099_0000.nii.gz',
   'label': './labelsTr/MSWAL_0099.nii.gz'},
  {'image': './imagesTr/MSWAL_0101_0000.nii.gz',
   'label': './labelsTr/MSWAL_0101.nii.gz'},
  {'image': './imagesTr/MSWAL_0102_0000.nii.gz',
   'label': './labelsTr/MSWAL_0102.nii.gz'},
  {'image': './imagesTr/MSWAL_0103_0000.nii.gz',
   'label': './labelsTr/MSWAL_0103.nii.gz'},
  {'image': './imagesTr/MSWAL_0104_0000.nii.gz',
   'label': './labelsTr/MSWAL_0104.nii.gz'},
  {'image': './imagesTr/MSWAL_0105_0000.nii.gz',
   'label': './labelsTr/MSWAL_0105.nii.gz'},
  {'image': './imagesTr/MSWAL_0106_0000.nii.gz',
   'label': './labelsTr/MSWAL_0106.nii.gz'},
  {'image': './imagesTr/MSWAL_0108_0000.nii.gz',
   'label': './labelsTr/MSWAL_0108.nii.gz'},
  {'image': './imagesTr/MSWAL_0109_0000.nii.gz',
   'label': './labelsTr/MSWAL_0109.nii.gz'},
  {'image': './imagesTr/MSWAL_0110_0000.nii.gz',
   'label': './labelsTr/MSWAL_0110.nii.gz'},
  {'image': './imagesTr/MSWAL_0111_0000.nii.gz',
   'label': './labelsTr/MSWAL_0111.nii.gz'},
  {'image': './imagesTr/MSWAL_0112_0000.nii.gz',
   'label': './labelsTr/MSWAL_0112.nii.gz'},
  {'image': './imagesTr/MSWAL_0113_0000.nii.gz',
   'label': './labelsTr/MSWAL_0113.nii.gz'},
  {'image': './imagesTr/MSWAL_0114_0000.nii.gz',
   'label': './labelsTr/MSWAL_0114.nii.gz'},
  {'image': './imagesTr/MSWAL_0117_0000.nii.gz',
   'label': './labelsTr/MSWAL_0117.nii.gz'},
  {'image': './imagesTr/MSWAL_0119_0000.nii.gz',
   'label': './labelsTr/MSWAL_0119.nii.gz'},
  {'image': './imagesTr/MSWAL_0120_0000.nii.gz',
   'label': './labelsTr/MSWAL_0120.nii.gz'},
  {'image': './imagesTr/MSWAL_0122_0000.nii.gz',
   'label': './labelsTr/MSWAL_0122.nii.gz'},
  {'image': './imagesTr/MSWAL_0124_0000.nii.gz',
   'label': './labelsTr/MSWAL_0124.nii.gz'},
  {'image': './imagesTr/MSWAL_0125_0000.nii.gz',
   'label': './labelsTr/MSWAL_0125.nii.gz'},
  {'image': './imagesTr/MSWAL_0126_0000.nii.gz',
   'label': './labelsTr/MSWAL_0126.nii.gz'},
  {'image': './imagesTr/MSWAL_0127_0000.nii.gz',
   'label': './labelsTr/MSWAL_0127.nii.gz'},
  {'image': './imagesTr/MSWAL_0128_0000.nii.gz',
   'label': './labelsTr/MSWAL_0128.nii.gz'},
  {'image': './imagesTr/MSWAL_0129_0000.nii.gz',
   'label': './labelsTr/MSWAL_0129.nii.gz'},
  {'image': './imagesTr/MSWAL_0130_0000.nii.gz',
   'label': './labelsTr/MSWAL_0130.nii.gz'},
  {'image': './imagesTr/MSWAL_0132_0000.nii.gz',
   'label': './labelsTr/MSWAL_0132.nii.gz'},
  {'image': './imagesTr/MSWAL_0133_0000.nii.gz',
   'label': './labelsTr/MSWAL_0133.nii.gz'},
  {'image': './imagesTr/MSWAL_0134_0000.nii.gz',
   'label': './labelsTr/MSWAL_0134.nii.gz'},
  {'image': './imagesTr/MSWAL_0136_0000.nii.gz',
   'label': './labelsTr/MSWAL_0136.nii.gz'},
  {'image': './imagesTr/MSWAL_0138_0000.nii.gz',
   'label': './labelsTr/MSWAL_0138.nii.gz'},
  {'image': './imagesTr/MSWAL_0139_0000.nii.gz',
   'label': './labelsTr/MSWAL_0139.nii.gz'},
  {'image': './imagesTr/MSWAL_0140_0000.nii.gz',
   'label': './labelsTr/MSWAL_0140.nii.gz'},
  {'image': './imagesTr/MSWAL_0141_0000.nii.gz',
   'label': './labelsTr/MSWAL_0141.nii.gz'},
  {'image': './imagesTr/MSWAL_0142_0000.nii.gz',
   'label': './labelsTr/MSWAL_0142.nii.gz'},
  {'image': './imagesTr/MSWAL_0143_0000.nii.gz',
   'label': './labelsTr/MSWAL_0143.nii.gz'},
  {'image': './imagesTr/MSWAL_0145_0000.nii.gz',
   'label': './labelsTr/MSWAL_0145.nii.gz'},
  {'image': './imagesTr/MSWAL_0147_0000.nii.gz',
   'label': './labelsTr/MSWAL_0147.nii.gz'},
  {'image': './imagesTr/MSWAL_0148_0000.nii.gz',
   'label': './labelsTr/MSWAL_0148.nii.gz'},
  {'image': './imagesTr/MSWAL_0149_0000.nii.gz',
   'label': './labelsTr/MSWAL_0149.nii.gz'},
  {'image': './imagesTr/MSWAL_0150_0000.nii.gz',
   'label': './labelsTr/MSWAL_0150.nii.gz'},
  {'image': './imagesTr/MSWAL_0151_0000.nii.gz',
   'label': './labelsTr/MSWAL_0151.nii.gz'},
  {'image': './imagesTr/MSWAL_0152_0000.nii.gz',
   'label': './labelsTr/MSWAL_0152.nii.gz'},
  {'image': './imagesTr/MSWAL_0157_0000.nii.gz',
   'label': './labelsTr/MSWAL_0157.nii.gz'},
  {'image': './imagesTr/MSWAL_0159_0000.nii.gz',
   'label': './labelsTr/MSWAL_0159.nii.gz'},
  {'image': './imagesTr/MSWAL_0162_0000.nii.gz',
   'label': './labelsTr/MSWAL_0162.nii.gz'},
  {'image': './imagesTr/MSWAL_0163_0000.nii.gz',
   'label': './labelsTr/MSWAL_0163.nii.gz'},
  {'image': './imagesTr/MSWAL_0165_0000.nii.gz',
   'label': './labelsTr/MSWAL_0165.nii.gz'},
  {'image': './imagesTr/MSWAL_0166_0000.nii.gz',
   'label': './labelsTr/MSWAL_0166.nii.gz'},
  {'image': './imagesTr/MSWAL_0167_0000.nii.gz',
   'label': './labelsTr/MSWAL_0167.nii.gz'},
  {'image': './imagesTr/MSWAL_0168_0000.nii.gz',
   'label': './labelsTr/MSWAL_0168.nii.gz'},
  {'image': './imagesTr/MSWAL_0169_0000.nii.gz',
   'label': './labelsTr/MSWAL_0169.nii.gz'},
  {'image': './imagesTr/MSWAL_0170_0000.nii.gz',
   'label': './labelsTr/MSWAL_0170.nii.gz'},
  {'image': './imagesTr/MSWAL_0171_0000.nii.gz',
   'label': './labelsTr/MSWAL_0171.nii.gz'},
  {'image': './imagesTr/MSWAL_0172_0000.nii.gz',
   'label': './labelsTr/MSWAL_0172.nii.gz'},
  {'image': './imagesTr/MSWAL_0173_0000.nii.gz',
   'label': './labelsTr/MSWAL_0173.nii.gz'},
  {'image': './imagesTr/MSWAL_0174_0000.nii.gz',
   'label': './labelsTr/MSWAL_0174.nii.gz'},
  {'image': './imagesTr/MSWAL_0175_0000.nii.gz',
   'label': './labelsTr/MSWAL_0175.nii.gz'},
  {'image': './imagesTr/MSWAL_0176_0000.nii.gz',
   'label': './labelsTr/MSWAL_0176.nii.gz'},
  {'image': './imagesTr/MSWAL_0177_0000.nii.gz',
   'label': './labelsTr/MSWAL_0177.nii.gz'},
  {'image': './imagesTr/MSWAL_0178_0000.nii.gz',
   'label': './labelsTr/MSWAL_0178.nii.gz'},
  {'image': './imagesTr/MSWAL_0179_0000.nii.gz',
   'label': './labelsTr/MSWAL_0179.nii.gz'},
  {'image': './imagesTr/MSWAL_0180_0000.nii.gz',
   'label': './labelsTr/MSWAL_0180.nii.gz'},
  {'image': './imagesTr/MSWAL_0182_0000.nii.gz',
   'label': './labelsTr/MSWAL_0182.nii.gz'},
  {'image': './imagesTr/MSWAL_0183_0000.nii.gz',
   'label': './labelsTr/MSWAL_0183.nii.gz'},
  {'image': './imagesTr/MSWAL_0184_0000.nii.gz',
   'label': './labelsTr/MSWAL_0184.nii.gz'},
  {'image': './imagesTr/MSWAL_0185_0000.nii.gz',
   'label': './labelsTr/MSWAL_0185.nii.gz'},
  {'image': './imagesTr/MSWAL_0186_0000.nii.gz',
   'label': './labelsTr/MSWAL_0186.nii.gz'},
  {'image': './imagesTr/MSWAL_0187_0000.nii.gz',
   'label': './labelsTr/MSWAL_0187.nii.gz'},
  {'image': './imagesTr/MSWAL_0188_0000.nii.gz',
   'label': './labelsTr/MSWAL_0188.nii.gz'},
  {'image': './imagesTr/MSWAL_0189_0000.nii.gz',
   'label': './labelsTr/MSWAL_0189.nii.gz'},
  {'image': './imagesTr/MSWAL_0193_0000.nii.gz',
   'label': './labelsTr/MSWAL_0193.nii.gz'},
  {'image': './imagesTr/MSWAL_0194_0000.nii.gz',
   'label': './labelsTr/MSWAL_0194.nii.gz'},
  {'image': './imagesTr/MSWAL_0195_0000.nii.gz',
   'label': './labelsTr/MSWAL_0195.nii.gz'},
  {'image': './imagesTr/MSWAL_0199_0000.nii.gz',
   'label': './labelsTr/MSWAL_0199.nii.gz'},
  {'image': './imagesTr/MSWAL_0201_0000.nii.gz',
   'label': './labelsTr/MSWAL_0201.nii.gz'},
  {'image': './imagesTr/MSWAL_0202_0000.nii.gz',
   'label': './labelsTr/MSWAL_0202.nii.gz'},
  {'image': './imagesTr/MSWAL_0203_0000.nii.gz',
   'label': './labelsTr/MSWAL_0203.nii.gz'},
  {'image': './imagesTr/MSWAL_0204_0000.nii.gz',
   'label': './labelsTr/MSWAL_0204.nii.gz'},
  {'image': './imagesTr/MSWAL_0207_0000.nii.gz',
   'label': './labelsTr/MSWAL_0207.nii.gz'},
  {'image': './imagesTr/MSWAL_0208_0000.nii.gz',
   'label': './labelsTr/MSWAL_0208.nii.gz'},
  {'image': './imagesTr/MSWAL_0209_0000.nii.gz',
   'label': './labelsTr/MSWAL_0209.nii.gz'},
  {'image': './imagesTr/MSWAL_0214_0000.nii.gz',
   'label': './labelsTr/MSWAL_0214.nii.gz'},
  {'image': './imagesTr/MSWAL_0217_0000.nii.gz',
   'label': './labelsTr/MSWAL_0217.nii.gz'},
  {'image': './imagesTr/MSWAL_0218_0000.nii.gz',
   'label': './labelsTr/MSWAL_0218.nii.gz'},
  {'image': './imagesTr/MSWAL_0219_0000.nii.gz',
   'label': './labelsTr/MSWAL_0219.nii.gz'},
  {'image': './imagesTr/MSWAL_0220_0000.nii.gz',
   'label': './labelsTr/MSWAL_0220.nii.gz'},
  {'image': './imagesTr/MSWAL_0221_0000.nii.gz',
   'label': './labelsTr/MSWAL_0221.nii.gz'},
  {'image': './imagesTr/MSWAL_0222_0000.nii.gz',
   'label': './labelsTr/MSWAL_0222.nii.gz'},
  {'image': './imagesTr/MSWAL_0223_0000.nii.gz',
   'label': './labelsTr/MSWAL_0223.nii.gz'},
  {'image': './imagesTr/MSWAL_0224_0000.nii.gz',
   'label': './labelsTr/MSWAL_0224.nii.gz'},
  {'image': './imagesTr/MSWAL_0225_0000.nii.gz',
   'label': './labelsTr/MSWAL_0225.nii.gz'},
  {'image': './imagesTr/MSWAL_0226_0000.nii.gz',
   'label': './labelsTr/MSWAL_0226.nii.gz'},
  {'image': './imagesTr/MSWAL_0227_0000.nii.gz',
   'label': './labelsTr/MSWAL_0227.nii.gz'},
  {'image': './imagesTr/MSWAL_0228_0000.nii.gz',
   'label': './labelsTr/MSWAL_0228.nii.gz'},
  {'image': './imagesTr/MSWAL_0229_0000.nii.gz',
   'label': './labelsTr/MSWAL_0229.nii.gz'},
  {'image': './imagesTr/MSWAL_0230_0000.nii.gz',
   'label': './labelsTr/MSWAL_0230.nii.gz'},
  {'image': './imagesTr/MSWAL_0233_0000.nii.gz',
   'label': './labelsTr/MSWAL_0233.nii.gz'},
  {'image': './imagesTr/MSWAL_0234_0000.nii.gz',
   'label': './labelsTr/MSWAL_0234.nii.gz'},
  {'image': './imagesTr/MSWAL_0238_0000.nii.gz',
   'label': './labelsTr/MSWAL_0238.nii.gz'},
  {'image': './imagesTr/MSWAL_0241_0000.nii.gz',
   'label': './labelsTr/MSWAL_0241.nii.gz'},
  {'image': './imagesTr/MSWAL_0242_0000.nii.gz',
   'label': './labelsTr/MSWAL_0242.nii.gz'},
  {'image': './imagesTr/MSWAL_0243_0000.nii.gz',
   'label': './labelsTr/MSWAL_0243.nii.gz'},
  {'image': './imagesTr/MSWAL_0245_0000.nii.gz',
   'label': './labelsTr/MSWAL_0245.nii.gz'},
  {'image': './imagesTr/MSWAL_0246_0000.nii.gz',
   'label': './labelsTr/MSWAL_0246.nii.gz'},
  {'image': './imagesTr/MSWAL_0247_0000.nii.gz',
   'label': './labelsTr/MSWAL_0247.nii.gz'},
  {'image': './imagesTr/MSWAL_0248_0000.nii.gz',
   'label': './labelsTr/MSWAL_0248.nii.gz'},
  {'image': './imagesTr/MSWAL_0251_0000.nii.gz',
   'label': './labelsTr/MSWAL_0251.nii.gz'},
  {'image': './imagesTr/MSWAL_0252_0000.nii.gz',
   'label': './labelsTr/MSWAL_0252.nii.gz'},
  {'image': './imagesTr/MSWAL_0253_0000.nii.gz',
   'label': './labelsTr/MSWAL_0253.nii.gz'},
  {'image': './imagesTr/MSWAL_0254_0000.nii.gz',
   'label': './labelsTr/MSWAL_0254.nii.gz'},
  {'image': './imagesTr/MSWAL_0255_0000.nii.gz',
   'label': './labelsTr/MSWAL_0255.nii.gz'},
  {'image': './imagesTr/MSWAL_0256_0000.nii.gz',
   'label': './labelsTr/MSWAL_0256.nii.gz'},
  {'image': './imagesTr/MSWAL_0257_0000.nii.gz',
   'label': './labelsTr/MSWAL_0257.nii.gz'},
  {'image': './imagesTr/MSWAL_0258_0000.nii.gz',
   'label': './labelsTr/MSWAL_0258.nii.gz'},
  {'image': './imagesTr/MSWAL_0259_0000.nii.gz',
   'label': './labelsTr/MSWAL_0259.nii.gz'},
  {'image': './imagesTr/MSWAL_0260_0000.nii.gz',
   'label': './labelsTr/MSWAL_0260.nii.gz'},
  {'image': './imagesTr/MSWAL_0261_0000.nii.gz',
   'label': './labelsTr/MSWAL_0261.nii.gz'},
  {'image': './imagesTr/MSWAL_0262_0000.nii.gz',
   'label': './labelsTr/MSWAL_0262.nii.gz'},
  {'image': './imagesTr/MSWAL_0263_0000.nii.gz',
   'label': './labelsTr/MSWAL_0263.nii.gz'},
  {'image': './imagesTr/MSWAL_0264_0000.nii.gz',
   'label': './labelsTr/MSWAL_0264.nii.gz'},
  {'image': './imagesTr/MSWAL_0265_0000.nii.gz',
   'label': './labelsTr/MSWAL_0265.nii.gz'},
  {'image': './imagesTr/MSWAL_0267_0000.nii.gz',
   'label': './labelsTr/MSWAL_0267.nii.gz'},
  {'image': './imagesTr/MSWAL_0270_0000.nii.gz',
   'label': './labelsTr/MSWAL_0270.nii.gz'},
  {'image': './imagesTr/MSWAL_0271_0000.nii.gz',
   'label': './labelsTr/MSWAL_0271.nii.gz'},
  {'image': './imagesTr/MSWAL_0272_0000.nii.gz',
   'label': './labelsTr/MSWAL_0272.nii.gz'},
  {'image': './imagesTr/MSWAL_0273_0000.nii.gz',
   'label': './labelsTr/MSWAL_0273.nii.gz'},
  {'image': './imagesTr/MSWAL_0274_0000.nii.gz',
   'label': './labelsTr/MSWAL_0274.nii.gz'},
  {'image': './imagesTr/MSWAL_0275_0000.nii.gz',
   'label': './labelsTr/MSWAL_0275.nii.gz'},
  {'image': './imagesTr/MSWAL_0276_0000.nii.gz',
   'label': './labelsTr/MSWAL_0276.nii.gz'},
  {'image': './imagesTr/MSWAL_0277_0000.nii.gz',
   'label': './labelsTr/MSWAL_0277.nii.gz'},
  {'image': './imagesTr/MSWAL_0278_0000.nii.gz',
   'label': './labelsTr/MSWAL_0278.nii.gz'},
  {'image': './imagesTr/MSWAL_0279_0000.nii.gz',
   'label': './labelsTr/MSWAL_0279.nii.gz'},
  {'image': './imagesTr/MSWAL_0281_0000.nii.gz',
   'label': './labelsTr/MSWAL_0281.nii.gz'},
  {'image': './imagesTr/MSWAL_0282_0000.nii.gz',
   'label': './labelsTr/MSWAL_0282.nii.gz'},
  {'image': './imagesTr/MSWAL_0283_0000.nii.gz',
   'label': './labelsTr/MSWAL_0283.nii.gz'},
  {'image': './imagesTr/MSWAL_0284_0000.nii.gz',
   'label': './labelsTr/MSWAL_0284.nii.gz'},
  {'image': './imagesTr/MSWAL_0285_0000.nii.gz',
   'label': './labelsTr/MSWAL_0285.nii.gz'},
  {'image': './imagesTr/MSWAL_0288_0000.nii.gz',
   'label': './labelsTr/MSWAL_0288.nii.gz'},
  {'image': './imagesTr/MSWAL_0289_0000.nii.gz',
   'label': './labelsTr/MSWAL_0289.nii.gz'},
  {'image': './imagesTr/MSWAL_0290_0000.nii.gz',
   'label': './labelsTr/MSWAL_0290.nii.gz'},
  {'image': './imagesTr/MSWAL_0293_0000.nii.gz',
   'label': './labelsTr/MSWAL_0293.nii.gz'},
  {'image': './imagesTr/MSWAL_0296_0000.nii.gz',

In [26]:
labels = dataset["labels"]
labels = ", ".join([k for k, _ in labels.items() if k != "background"])
print(labels)

gallstone, kidney stone, liver tumor, kidney tumor, pancreatic cancer, liver cyst, kidney cyst

In [28]:
index_df["ROINames"] = labels
index_df

,Split,ImageID,filepath,file_type,reference_id,class,hash,size,ndim,nvoxels,...,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality,BodyPartExamined,ROINames
0,Tr,1,imagesTr/MSWAL_0001_0000.nii.gz,scan,Tr_1,MedImage,ec117e20f6d9e39b42bfcb5988e821eb1a066165,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
1,Tr,2,imagesTr/MSWAL_0002_0000.nii.gz,scan,Tr_2,MedImage,5041b6c35a82c0fea483e97460b690d66087ab6e,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
2,Tr,3,imagesTr/MSWAL_0003_0000.nii.gz,scan,Tr_3,MedImage,67cb8cf2c2c31e405099da93f5b0f4fc56856744,"(512, 512, 381)",3,99876864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
3,Tr,8,imagesTr/MSWAL_0008_0000.nii.gz,scan,Tr_8,MedImage,f716e03e231ad3e07b4adfc28ea701cab38842ee,"(512, 512, 201)",3,52690944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
4,Tr,9,imagesTr/MSWAL_0009_0000.nii.gz,scan,Tr_9,MedImage,d75e77b78dc96498200fd8c59de83d4e7c168989,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,Tr,688,labelsTr/MSWAL_0688.nii.gz,mask,Tr_688,Mask,6e87ecb0b91396de2aa79ac5a2a83955f1fe7f42,"(512, 512, 474)",3,124256256,...,2.486319,2.196475,13.487813,2286.087942,"(11.307281870773021, 28.113509098844226, 61.75...",22.0,imagesTr/MSWAL_0688_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
964,Tr,690,labelsTr/MSWAL_0690.nii.gz,mask,Tr_690,Mask,b9aa4bf64397d62bffd687ebf23ac35765441b26,"(512, 512, 523)",3,137101312,...,1.451475,1.785663,43.438991,23712.062073,"(55.860323267234016, 81.07988364160474, 144.78...",20.0,imagesTr/MSWAL_0690_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
965,Tr,692,labelsTr/MSWAL_0692.nii.gz,mask,Tr_692,Mask,20ebed3cc05afe10a9e268c3ace9d45a3ae3e5c0,"(512, 512, 293)",3,76808192,...,1.843109,1.619462,15.214846,2909.008483,"(17.2374613949725, 31.770517222565385, 51.4511...",3.0,imagesTr/MSWAL_0692_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
966,Tr,693,labelsTr/MSWAL_0693.nii.gz,mask,Tr_693,Mask,c357b6330f01eadd8ceb0d4f2a33d73603169e38,"(512, 512, 240)",3,62914560,...,4.158035,2.385840,10.546019,1397.613227,"(6.104443010089622, 25.382488557742494, 60.558...",7.0,imagesTr/MSWAL_0693_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
967,Tr,694,labelsTr/MSWAL_0694.nii.gz,mask,Tr_694,Mask,d050aef1c1a4642607a55f5da6de4f5502d006ad,"(512, 512, 276)",3,72351744,...,1.405936,1.271195,3.579363,160.998309,"(5.265681523245576, 7.403213210767661, 9.41092...",1.0,imagesTr/MSWAL_0694_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."

In [29]:
index_df.to_csv(indexed_datasets.imgtools_path / "MSWAL" / "index.csv", index=False)

In [1]:
from imgnet.collections.store import IndexedDatasets

indexed_datasets = IndexedDatasets()

/home/gpudual/bhklab/josh/med-image_index/.pixi/envs/default/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
14:31:59 [info     ] Indexed datasets path: /home/gpudual/.local/share/med-imagenet/indexed_datasets [imgnet] call=store.__init__:67

In [3]:
from imgindex.model import validate_index

index = indexed_datasets.index("MSWAL")
validate_index(index, "nifti", lazy=True)

Invalid NIFTI index: {
    "SCHEMA": {
        "COLUMN_NOT_IN_DATAFRAME": [
            {
                "schema": "NiftiIndex",
                "column": "NiftiIndex",
                "check": "column_in_dataframe",
                "error": "column 'SampleID' not in dataframe. Columns in dataframe: ['Split', 'ImageID', 'filepath', 'file_type', 'reference_id', 'class', 'hash', 'size', 'ndim', 'nvoxels', 'spacing', 'origin', 'direction', 'min', 'max', 'sum', 'mean', 'std', 'variance', 'dtype_str', 'dtype_numpy', 'mask.bbox.size', 'mask.bbox.min_coord', 'mask.bbox.max_coord', 'mask.feret_diameter', 'mask.roundness', 'mask.flatness', 'mask.elongation', 'mask.equivalent_spherical_radius', 'mask.equivalent_spherical_perimeter', 'mask.equivalent_ellipsoid_diameters', 'mask.volume_count', 'reference_scan', 'Modality', 'BodyPartExamined', 'ROINames']"
            }
        ]
    }
}

In [4]:
index.rename(columns={"reference_id": "SampleID"}, inplace=True)

In [5]:
new_index = validate_index(index, "nifti", lazy=True)

In [6]:
new_index

,Split,ImageID,filepath,file_type,SampleID,class,hash,size,ndim,nvoxels,...,mask.flatness,mask.elongation,mask.equivalent_spherical_radius,mask.equivalent_spherical_perimeter,mask.equivalent_ellipsoid_diameters,mask.volume_count,reference_scan,Modality,BodyPartExamined,ROINames
0,Tr,1,imagesTr/MSWAL_0001_0000.nii.gz,scan,Tr_1,MedImage,ec117e20f6d9e39b42bfcb5988e821eb1a066165,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
1,Tr,2,imagesTr/MSWAL_0002_0000.nii.gz,scan,Tr_2,MedImage,5041b6c35a82c0fea483e97460b690d66087ab6e,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
2,Tr,3,imagesTr/MSWAL_0003_0000.nii.gz,scan,Tr_3,MedImage,67cb8cf2c2c31e405099da93f5b0f4fc56856744,"(512, 512, 381)",3,99876864,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
3,Tr,8,imagesTr/MSWAL_0008_0000.nii.gz,scan,Tr_8,MedImage,f716e03e231ad3e07b4adfc28ea701cab38842ee,"(512, 512, 201)",3,52690944,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
4,Tr,9,imagesTr/MSWAL_0009_0000.nii.gz,scan,Tr_9,MedImage,d75e77b78dc96498200fd8c59de83d4e7c168989,"(512, 512, 177)",3,46399488,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CT,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
963,Tr,688,labelsTr/MSWAL_0688.nii.gz,mask,Tr_688,Mask,6e87ecb0b91396de2aa79ac5a2a83955f1fe7f42,"(512, 512, 474)",3,124256256,...,2.486319,2.196475,13.487813,2286.087942,"(11.307281870773021, 28.113509098844226, 61.75...",22.0,imagesTr/MSWAL_0688_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
964,Tr,690,labelsTr/MSWAL_0690.nii.gz,mask,Tr_690,Mask,b9aa4bf64397d62bffd687ebf23ac35765441b26,"(512, 512, 523)",3,137101312,...,1.451475,1.785663,43.438991,23712.062073,"(55.860323267234016, 81.07988364160474, 144.78...",20.0,imagesTr/MSWAL_0690_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
965,Tr,692,labelsTr/MSWAL_0692.nii.gz,mask,Tr_692,Mask,20ebed3cc05afe10a9e268c3ace9d45a3ae3e5c0,"(512, 512, 293)",3,76808192,...,1.843109,1.619462,15.214846,2909.008483,"(17.2374613949725, 31.770517222565385, 51.4511...",3.0,imagesTr/MSWAL_0692_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
966,Tr,693,labelsTr/MSWAL_0693.nii.gz,mask,Tr_693,Mask,c357b6330f01eadd8ceb0d4f2a33d73603169e38,"(512, 512, 240)",3,62914560,...,4.158035,2.385840,10.546019,1397.613227,"(6.104443010089622, 25.382488557742494, 60.558...",7.0,imagesTr/MSWAL_0693_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."
967,Tr,694,labelsTr/MSWAL_0694.nii.gz,mask,Tr_694,Mask,d050aef1c1a4642607a55f5da6de4f5502d006ad,"(512, 512, 276)",3,72351744,...,1.405936,1.271195,3.579363,160.998309,"(5.265681523245576, 7.403213210767661, 9.41092...",1.0,imagesTr/MSWAL_0694_0000.nii.gz,SEG,Abdomen,"gallstone, kidney stone, liver tumor, kidney t..."

In [7]:
from pathlib import Path

new_index_dir = Path("/home/gpudual/bhklab/josh/med-image_index/new_index")
collection_path = new_index_dir / "MSWAL"
collection_path.mkdir(parents=True, exist_ok=True)

new_index.to_csv(collection_path / "index.csv", index=False)

In [4]:
import json
from pathlib import Path
source = indexed_datasets.source_config("MSWAL")
new_index_dir = Path("/home/gpudual/bhklab/josh/med-image_index/new_index")

collection_path = new_index_dir / "MSWAL"

with open(collection_path / "source.json", "w") as f:
    json.dump(source.model_dump(mode="json"), f, indent=2)

In [9]:
print([col for col in indexed_datasets.collections if indexed_datasets.file_type(col).value == "nifti"])

['AMOS', 'HCUCH-recist-dataset', 'MSWAL', 'MedicalDecathalon', 'Totalsegmentator', 'TotalsegmentatorMRI']